---
title: "Historical Alberta Wildfire Data"
toc: true
toc-depth: 4
toc-location: right
sidebar: false
---

::: {.callout-note icon="terminal" title="Try it live!"}
Use Binder to explore and run this dataset and analysis interactively in your browser with `R`. Ideal for students and instructors to run, modify, and test the analysis in a live JupyterLab environment—no setup needed.

👉 [Launch on Binder](https://mybinder.org/v2/gh/jadeeechen/diversedata-notebooks/HEAD?urlpath=lab/tree/wildfire.ipynb){target="_blank" rel="noopener"}

:::

## About the Data

This data set contains information on wildfires in Canada, compiled from official government sources under the Open Government Licence – Alberta.

The data was gathered to monitor, assess, and respond to wildfire risks across different regions. Wildfires have far-reaching environmental, social, and economic consequences. From an equity and inclusion perspective, analyzing wildfire data can reveal geographic and resource-based disparities in detection and containment efforts, and highlight how certain populations face greater risks due to climate change and limited infrastructure.

In particular, Alberta experiences some of the most severe and frequent wildfires in Canada due to its vast forested areas, dry climate, and increasing temperatures linked to climate change. Wildfires in Alberta can lead to widespread evacuations, destroy homes and livelihoods, and disproportionately affect rural and Indigenous communities, who may lack access to adequate emergency services and infrastructure. Understanding the patterns of wildfire occurrence and spread helps policymakers, environmental planners, and emergency services allocate resources more equitably and implement effective mitigation strategies. This data set enables data-driven approaches to reduce the impact of wildfires and support more resilient and inclusive disaster management practices across Alberta and beyond.

### Download

<div class="button-container">
  <a href="../../data/clean/wildfire.csv" download class="download-button">
    Download CSV
  </a>
</div>

### Metadata

<div class="description-grid">
  <div class="field-label">CSV Name</div><div class="field-value">wildfire.csv</div>
  <div class="field-label">Data Set Characteristics</div><div class="field-value">Multivariate</div>
  <div class="field-label">Subject Area</div><div class="field-value">Climate Change</div>
  <div class="field-label">Associated Tasks</div><div class="field-value">Classification, Time Series, Geospatial Analysis</div>
  <div class="field-label">Feature Type</div><div class="field-value">Categorical, Integer</div>
  <div class="field-label">Instances</div><div class="field-value">26551 records</div>
  <div class="field-label">Features</div><div class="field-value">50</div>
  <div class="field-label">Has Missing Values?</div><div class="field-value">Yes</div>
</div>

### Variables

::: {.table-container}
::: {.styled-table}

| Variable Name                  | Role     | Type        | Description                                                                                       | Units         | Missing Values |
|--------------------------------|----------|-------------|---------------------------------------------------------------------------------------------------|---------------|----------------|
| `year`                         | ID       | Integer     | Year in which the wildfire was first detected incident                                            | Year          | No             |
| `fire_number`                  | ID       | String      | Identifier for the wildfire                                                                       | -             | No             |
| `current_size`                 | Feature  | Numeric     | Final estimated area burned by the wildfire                                                       | Hectares      | No             |
| `size_class`                   | Feature  | Categorical | Size classification based on final area burned                                                    | -             | No             |
| `latitude`                     | Feature  | Numeric     | Latitude coordinate of the wildfire origin                                                        | Degrees       | No             |
| `longitude`                    | Feature  | Numeric     | Longitude coordinate of the wildfire origin                                                       | Degrees       | No             |
| `fire_origin`                  | Metadata | Categorical | Who owns or administers the land the wildfire ignited on                                          | -             | No             |
| `general_cause`                | Feature  | Categorical | Classification of the wildfire cause                                                              | -             | No             |
| `responsible_group`            | Metadata | Categorical | Recreational group responsible for causing the wildfire                                           | -             | No             |
| `activity_class`               | Feature  | Categorical | Activity that was going on when the wildfire started                                              | -             | No             |
| `true_cause`                   | Feature  | Categorical | Specific reason why the wildfire started (e.g., "Arson Known", "Hot Exhaust", "Line Impact", "Unattended Fire", etc.) | -             | No              |
| `fire_start_date`              | Time     | Date        | Datetime the wildfire started                                                                     | YYYY-MM-DD    | Yes            |
| `detection_agent_type`         | Feature  | Categorical | Type of detection agent that discovered the wildfire (e.g., lookout ("LKT"), aircraft ("AIR"))    | -             | No             |
| `detection_agent`              | Feature  | Categorical | Specific type of detection agent that discovered the wildfire                                     | -             | No             |
| `assessment_hectares`          | Feature  | Numeric     | Size of the wildfire at the time of assessment                                                    | Hectares      | No             |
| `fire_spread_rate`             | Feature  | Numeric     | Rate at which the wildfire spread at the time of initial assessment                               | Metres/minute | No             |
| `fire_type`                    | Feature  | Categorical | Predominant wildfire behavior classification at the time of initial assessment (e.g., "Surface", "Ground", "Crown") | -             | No             |
| `fire_position_on_slope`       | Feature  | Categorical | Position of the wildfire relative to the slope it is travelling on at the time of initial assessment (e.g., "Bottom", "Middle 1/3", "Unknown") | -             | No             |
| `weather_conditions_over_fire` | Feature  | Categorical | Weather conditions over the wildfire at the time of initial assessment                            | -             | No             |
| `temperature`                  | Feature  | Numeric     | Temperature at the wildfire location at the time of initial assessment                            | °C            | Yes            |
| `relative_humidity`            | Feature  | Numeric     | Relative humidity at the wildfire location at the time of initial assessment                      | %             | Yes            |
| `wind_direction`               | Feature  | Categorical | Wind direction at the wildfire location at the time of initial assessment                         | -             | No             |
| `wind_speed`                   | Feature  | Numeric     | Wind speed at the wildfire location in km/h at the time of initial assessment                     | km/h          | Yes            |
| `fuel_type`                    | Feature  | Categorical | Dominant fuel type (vegetation cover) in which the wildfire is burning at the wildfire location at the time of initial assessment | -             | No             |
| `initial_action_by`            | Metadata | Categorical | Group that initiated suppression efforts                                                          | -             | No             |
| `ia_arrival_at_fire_date`      | Time     | DateTime    | Datetime when the initial action group arrived at the wildfire                                    | YYYY-MM-DD    | Yes            |
| `ia_access`                    | Feature  | Categorical | Method of access that the initial action group used                                               | -             | No             |
| `fire_fighting_start_date`     | Time     | DateTime    | Datetime when the initial action group began firefighting activities                              | YYYY-MM-DD    | Yes            |
| `fire_fighting_start_size`     | Feature  | Numeric     | Wildfire size at the time firefighting began                                                      | Hectares      | No             |
| `bucketing_on_fire`            | Feature  | Binary      | Whether aerial bucketing was used on the wildfire                                                 | Yes/No        | No             |
| `first_bh_date`                | Time     | DateTime    | Datetime when wildfire was first declared being held                                              | YYYY-MM-DD    | No             |
| `first_bh_size`                | Feature  | Numeric     | Wildfire size when wildfire was first declared being held                                         | Hectares      | No             |
| `first_uc_date`                | Time     | DateTime    | Datetime when wildfire was first declared under control                                           | YYYY-MM-DD    | No             |
| `first_uc_size`                | Feature  | Numeric     | Wildfire size when first declared under control                                                   | Hectares      | No             |
| `first_ex_size_perimeter`      | Feature  | Numeric     | Wildfire size when first declared extinguished                                                    | Hectares      | No             |


:::
:::

{{< include ../notebooks/wildfire.qmd >}} 

## Attribution

Data sourced from the Government of Alberta via the Government of Canada's Open Government Portal, available under an [Open Government Licence - Alberta](https://open.alberta.ca/licence). Original data set: [Historical wildfire data: 2006-2024](https://open.canada.ca/data/en/dataset/a221e7a0-4f46-4be7-9c5a-e29de9a3447e).

