project:
  type: website
  output-dir: docs

website:
  title: "Diverse Data Hub"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: website_files/datasets.qmd
        text: Datasets
  sidebar:
    logo: "website_files/img/logo.png"
    style: "floating"
    search: false
    contents:
      - text: "CRAN Page (TBD)"
        href: ""
      - section: "Source Code"
        contents:
          - text: "GitHub"
            href: "https://github.com/diverse-data-hub/diversedata"
            icon: github
          - text: "Report an Issue"
            href: "https://github.com/diverse-data-hub/diversedata/issues"
      - text: "License (TBD)"
        href: ""
      - text: "Citation (TBD)"
        href: "https://diverse-data-hub.github.io/website_files/citation.html"
      - section: "Owners"
        contents:
          - text: "Katie Burak PhD"
            href: "https://github.com/katieburak"
          - text: "Elham E Khoda"
            href: "https://github.com/elhamekhoda"
      - section: "Collaborators"
        contents:
          - text: "Francisco Ramirez"
            href: "https://github.com/fraramfra"
          - text: "Azin Piran"
            href: "https://github.com/AzinPiran"
          - text: "Siddarth Subrahmanian"
            href: "https://github.com/siddart-1"

format:
  html:
    theme:
      - minty
      - website_files/styles.scss
    css: website_files/styles.css
    page-layout: full



