project:
  type: website
  render: 
    - "index.qmd"
    - "data/"
    - "website_files/description_pages/"
    - "website_files/grid_items/"
    - "website_files/img/"
    - "website_files/citation.qmd"
    - "website_files/collaborate.qmd"
    - "website_files/datasets.qmd"
    - "!scripts/"
    - "!website_files/notebooks/"

website:

  title: "Diverse Data Hub"

  favicon: website_files/img/favicon.png

  navbar:
    left:
      - href: website_files/datasets.qmd
        text: Data Sets
      - href: website_files/citation.qmd
        text: Citation
      - href: website_files/collaborate.qmd
        text: Collaborate

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    background: "rgb(146, 191, 218)"

  sidebar:

    logo: "website_files/img/logo.png"
    style: "floating"
    search: false
    align: center
    tools: 
      - icon: github
        href: https://github.com/diverse-data-hub
    collapse-level: 1
  google-analytics: "G-4QQCPMY56L"


format:
  html:
    theme:
      - minty
      - website_files/styles.scss
    css: website_files/styles.css
    page-layout: full
    toc: true
    toc-location: left
    fontsize: 1.125em



