project:
  type: website
  output-dir: docs

website:
  title: "Diverse Data Hub"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: website_files/datasets.qmd
        text: All The Datasets
      - href: website_files/description_pages/marchmadness.qmd
        text: MarchMadness

format:
  html:
    theme: minty
    css: website_files/styles.css
    page-layout: full



