# To create environment from scratch:
# conda create -n diverse_web_env -c conda-forge python pandas jupyterlab altair matplotlib ...

# To create environment.yml with dependencies that were explicitly conda installed:
# conda env export -f environment.yml --from-history

# To create environment from yml file:
# conda env create --file environment.yml

# To delete environment:
# conda env remove -n diverse_web_env

# To activate environment:
# conda activate diverse_web_env

name: diverse_web_env
channels:
  - conda-forge
  - defaults
dependencies:
# for data cleaning notebooks in the scripts/ folder
  - python=3.12
  - jupyterlab=4.4.1   # also for interactive binder: JupyterLab option
  - ipykernel
  - pandas=2.2.3
  - altair=5.5.0
  - matplotlib=3.10.1
  - seaborn=0.13.2

# for interactive binder
  - r-base>=4.2         # R base packages
  - r-essentials        # IRkernel + common R packages

# for the Women's March Madness analysis in addition to pandas and altair
  - statsmodels=0.14
  - tabulate=0.9
  - pip
  - pip:
      - diversedata

# for the Gender Assessment analysis (additional to what's listed above)
  - scikit-posthocs=0.11

# for the How Couples Meet and Stay Together analysis (additional to what's listed above)
  - scikit-learn=1.7
