# To create environment from scratch:
# conda create -n diverse_web_env -c conda-forge python pandas jupyterlab altair matplotlib

# To create environment.yml:
# conda env export -f environment.yml --from-history

# To create environment from yml file:
# conda env create --file environment.yml

# To delete environment:
# conda env remove -n diverse_web_env

# To activate environment:
# conda activate diverse_web_env

name: diverse_web_env
channels:
  - conda-forge
  - defaults
dependencies:
# for data cleaning notebooks in the scripts/ folder
  - pandas=2.2.3
  - altair=5.5.0
  - jupyterlab=4.4.1   # also for interactive binder: JupyterLab option
  - python=3.12
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - r-irkernel

# for interactive binder
  - r-base>=4.2         # R base packages
  - r-essentials        # IRkernel + common R packages

# for 