::: {.hero-banner}

**Diverse Data Hub** is an open educational resource offering curated data sets focused on equity, diversity, inclusion, and other socially relevant topics. It is designed to support students, educators, and researchers in accessing and working with meaningful data.

Data sets are available through the `diversedata` R and Python package, allowing for straightforward integration into data science workflows. Each data set includes detailed documentation and contextual background to support informed exploration and connection to real-world topics. Example case studies are also included to illustrate practical applications.
:::

## Featured Data Sets 

<div class="grid-container featured-section">

<!-- These are the featured data sets -->

{{< include website_files/grid_items/marchmadness.qmd >}}
{{< include website_files/grid_items/bcindigenousbiz.qmd >}}

<!-- These are NOT featured data sets -->

<!-- {{< include website_files/grid_items/hcmst.qmd >}} -->
<!-- {{< include website_files/grid_items/wildfire.qmd >}} -->
<!-- {{< include website_files/grid_items/genderassessment.qmd >}} -->
<!-- {{< include website_files/grid_items/globalrights.qmd >}} -->

</div>

## Install `diversedata`

::: {.panel-tabset}

### R Package

#### Prerequisites

- `R` (>= 3.5): Download from [CRAN](https://cran.r-project.org/)

- `devtools` (R package)  
  ```r
  install.packages("devtools")
  ```

#### Installation

Install `diversedata` directly from GitHub using:

``` r
devtools::install_github("diverse-data-hub/diversedata")
```

#### Usage

Once installed, you can explore the available data sets and their documentation:

``` r
library(diversedata)

# List available data sets
data(package = "diversedata")

# View documentation for a specific data set
?wildfire

# To load a data set into the environment:
data("wildfire")
```

### Python Package

#### Prerequisites

- `Python` (>= 3.12) & `pip`: Download from [python.org](https://www.python.org/)

- `pandas` Python package (>= 2.3.1): This will be installed automatically when the `diversedata` Python package is installed via pip

#### Installation

The `diversedata` Python package can be installed via pip:

```bash
pip install diversedata
```

#### Usage

Once installed, you can explore the available data sets and their documentation:

```python
import diversedata as dd

# List available datasets
dd.list_available_datasets()

# View documentation for a specific dataset
dd.print_data_description('wildfire')

# To load a dataset and save it to an object:
df = dd.load_data('wildfire')
```
:::

## License

CC BY 4.0

[Full License](https://github.com/diverse-data-hub/diverse-data-hub.github.io/blob/main/LICENSE)

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const allItems = document.querySelectorAll(".grid-container-3 .grid-item");
    allItems.forEach(item => {
      if (item.dataset.featured === "true") {
        item.style.display = "block";
      } else {
        item.style.display = "none";
      }
    });
  });
</script>