#To create site-environment from scratch:
#conda create -n mds_capstone_v1 -c conda-forge python pandas jupyterlab altair matplotlib

#To create site-environment.yml:
#conda env export -f site-environment.yaml --from-history

#To create site-environment from yml file:
#conda env create --file site-environment.yml

#To delete site-environment:
#conda env remove -n mds_capstone_v1

#To activate site-environment:
#conda activate mds_capstone_v1

name: mds_capstone_v1
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.3
  - altair=5.5.0
  - jupyterlab=4.4.1
  - python=3.13.3
  - matplotlib=3.10.1
  - seaborn=0.13.2