{
  "hash": "8fbd3949cc1e7218464e39c145b8172c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Post-Graduation Income\"\ntoc: true\ntoc-depth: 4\ntoc-location: right\nsidebar: false\n---\n\n<!-- ::: {.callout-note icon=\"terminal\" title=\"Try it live!\"} -->\n<!-- Use Binder to explore and run this dataset and analysis interactively in your browser with `R`. Ideal for students and instructors to run, modify, and test the analysis in a live JupyterLab environment—no setup needed.  -->\n\n<!-- 👉 [Launch on Binder](https://mybinder.org/v2/gh/jadeeechen/diversedata-notebooks/HEAD?urlpath=lab/tree/wildfire.ipynb){target=\"_blank\" rel=\"noopener\"} -->\n\n<!-- ::: -->\n\n## About the Data\n\nThis dataset contains information on median income of Canadian students two years after graduation, compiled by Statistics Canada under the Open Government Licence – Canada. \n\nThe data was gathered to assess and understand economic outcomes and income distributions across diverse demographic and educational segments. From an equity and inclusion perspective, analyzing income data can reveal systemic disparities in post-graduation financial outcomes, shedding light on how factors like gender, ethnicity, and educational field and qualifications intersect with earnings. \n\nIn Canada, economic outcomes can vary significantly across different fields of study and demographic backgrounds, reflecting broader labor market dynamics and structural barriers. Disparities in income can limit financial stability, career advancement, and long-term economic mobility for underrepresented or marginalized groups. Understanding these disparities helps policymakers, educational institutions, and labor planners design targeted interventions with the hope of minimizing persistent wage gaps and promoting equitable career pathways. \n\n\n### Download\n\n<div class=\"button-container\">\n  <a href=\"../../data/clean/postgradincome.csv\" download class=\"download-button\">\n    Download CSV\n  </a>\n</div>\n\n### Metadata\n\n<div class=\"description-grid\">\n  <div class=\"field-label\">CSV Name</div><div class=\"field-value\">postgradincome.csv</div>\n  <div class=\"field-label\">Dataset Characteristics</div><div class=\"field-value\">Multivariate</div>\n  <div class=\"field-label\">Subject Area</div><div class=\"field-value\">Equity, Education, Income Disparity</div>\n  <div class=\"field-label\">Associated Tasks</div><div class=\"field-value\">Comparative Analysis, ...</div>\n  <div class=\"field-label\">Feature Type</div><div class=\"field-value\">Categorical, Numeric</div>\n  <div class=\"field-label\">Instances</div><div class=\"field-value\">16,636 records</div>\n  <div class=\"field-label\">Features</div><div class=\"field-value\">9</div>\n  <div class=\"field-label\">Has Missing Values?</div><div class=\"field-value\">No</div>\n</div>\n\n### Variables\n\n::: {.table-container}\n::: {.styled-table}\n\n| Variable Name                  | Role     | Type        | Description         | Units         | Missing Values |\n|--------------------------------|----------|-------------|---------------------------------------------------------------------------------------------------|---------------|----------------|\n| `year`         | ID       | Integer     | Year    | Year          | No             |\n| `location`     | Feature       | Categorical     | Geographical location, e.g. \"Canada\", \"Quebec\", etc.| - | No |\n| `educational_qualification`  | Feature    | Categorical     | Type of educational degree received, e.g. \"Undergraduate degree\"    | -      | No     |\n| `field_of_study`    | Feature       | Categorical     | Topic studied, e.g. \"Health and related fields\"  | -  | No     |\n| `gender`    | Feature       | Categorical     | \"Woman\", \"Man\", or \"Total\"    | -       | No             |\n| `age_group`  | Feature       | Categorial     | Range of ages, e.g. \"15 to 34 years\"    | -      | No       |\n| `population_group`   | Feature       | Categorical     | Population group, e.g. \"South Asian\", \"Black\", \"Visible minority population\"    | -          | No             |\n| `median_income` | Feature       | Integer     | Median reported income    | 2024 constant Canadian dollars     | No         |\n| `number_graduates` | Feature       | Integer     | Number of graduates who reported income    | -    | No         |\n\n:::\n:::\n\n\n::: {.cell}\n\n:::\n\n\n### Key Features of the Dataset\n\nEach row of this dataset represents a group of graduates and reports the group's median income 2 years after graduation, along with demographic information about the group of graduates:\n\n- **Year** (`year`) -- The year in which income was reported\n- **Location** (`location`) -- The geographical location of the graduates\n- **Educational Information** (`educational_qualification`, `field_of_study`) -- Information on the type and focus of the degree received by the group of graduates\n- **Demographic Information** (`gender`, `age_group`, `population_group`) -- Demographic information on the gender, age, and population group (similar to ethnicity) of the group of graduates\n- **Median Income** (`median_income`) -- The median income of the group of graduates\n- **Number of Graduates** (`number_graduates`) -- The number of individuals that make up the group\n\n### Purpose and Use Cases\nThis dataset supports the analysis of: \n\n- **Demographic Equity & Disparities:** Examining wage gaps and income distribution across gender and population groups.\n- **Educational Return on Investment (ROI):** Evaluating how different educational qualifications and credential levels impact post-graduation incomes.\n- **Impact of Field of Study:** Comparing incomes across various academic disciplines, from professional and technical trades to the humanities and sciences.\n- **Predictive Modeling:** Building regression or machine learning baselines to estimate expected post-graduate income based on a combination of educational and demographic factors.\n- **Institutional & Policy Insights:** Informing career advisory strategies, educational planning, and equity initiatives for prospective students.\n\n## Case Study\n\n### Objective\nEquitable incomes for recent graduates are essential for inclusive labor markets and educational planning. This dataset provides information on post-graduation median incomes in Canada, allowing us to examine how factors like gender, ethnicity, education type, and field of study intersect and impact incomes. \n\nTo explore these dynamics, we focus on several key questions: \n\n- Is there evidence of income disparity by gender or ethnicity in recent graduates in Canada?\n- How do educational credentials and fields of study shape incomes across different groups? \n- To what extent can we predict post-graduation income using these academic and demographic factors? \n\nThrough statistical testing and predictive modeling, we aim to uncover structural wage gaps and identify the primary drivers of post-grad earnings.\n\n### Analysis\n\n**Loading Libraries**\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\nlibrary(diversedata)      # Diverse Data Hub datasets\n\n# Core libraries\nlibrary(tidyverse)        \nlibrary(lubridate)      \nlibrary(stringr)\n\n# Plotting\nlibrary(ggdist)\n\n# Hypothesis testing\nlibrary(car)\nlibrary(FSA)\n\n# Modelling\nlibrary(rsample)\n\n# Tables & reporting\nlibrary(gt)               \nlibrary(kableExtra)       \n```\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nimport diversedata as dd\nimport numpy as np\nimport pandas as pd\nfrom IPython.display import Markdown\n\n# Plotting\nimport matplotlib.pyplot as plt\nimport matplotlib.ticker as ticker\nimport seaborn as sns\nimport textwrap\n\n# Hypothesis Testing\nimport statsmodels.api as sm\nimport statsmodels.formula.api as smf\nfrom scipy import stats\nimport scikit_posthocs as sp\n\n# Modelling\nfrom sklearn.model_selection import train_test_split\n```\n:::\n\n:::\n\n#### 1. Data Cleaning & Processing\nTo clean the data, first we use regex to clean the values in `field_of_study` and remove unnecessary numerical markers, like `[1]`. Then, we convert relevant columns to factor type. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_data <- postgradincome |>\n  mutate(\n    field_of_study = str_remove(field_of_study, \"\\\\s*\\\\[\\\\d+\\\\]$\"),\n    across(\n      c(location, educational_qualification, field_of_study, gender, age_group, population_group), \n      as.factor\n    )\n  ) \n\n# preview data\nincome_data |>\n  head() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| year|location |educational_qualification                              |field_of_study                                  |gender |age_group      |population_group       | median_income| number_graduates|\n|----:|:--------|:------------------------------------------------------|:-----------------------------------------------|:------|:--------------|:----------------------|-------------:|----------------:|\n| 2014|Alberta  |Career, technical or professional training certificate |Agriculture, natural resources and conservation |Man    |15 to 34 years |Not a visible minority |         52800|               70|\n| 2014|Alberta  |Career, technical or professional training certificate |Agriculture, natural resources and conservation |Woman  |15 to 34 years |Not a visible minority |         36600|              100|\n| 2014|Alberta  |Career, technical or professional training certificate |Architecture, engineering, and related trades   |Man    |15 to 34 years |Not a visible minority |         72300|              460|\n| 2014|Alberta  |Career, technical or professional training certificate |Architecture, engineering, and related trades   |Man    |15 to 34 years |South Asian            |         60200|               20|\n| 2014|Alberta  |Career, technical or professional training certificate |Architecture, engineering, and related trades   |Man    |35 to 64 years |Not a visible minority |        103200|              120|\n| 2014|Alberta  |Career, technical or professional training certificate |Architecture, engineering, and related trades   |Man    |35 to 64 years |South Asian            |         78700|               40|\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nincome_data = dd.load_data(\"postgradincome\")\nincome_data['field_of_study'] = income_data['field_of_study'].str.replace(r\"\\s*\\[\\d+\\]$\", \"\", regex=True)\n\ncols_to_factor = [\n  \"location\", \n  \"educational_qualification\",\n    \"field_of_study\",\n    \"gender\",\n    \"age_group\",\n    \"population_group\"\n]\n\nincome_data[cols_to_factor] = income_data[cols_to_factor].astype(\"category\")\n\nMarkdown(income_data.head().to_markdown())\n```\n\n::: {.cell-output-display}\n|    |   year | location   | educational_qualification                              | field_of_study                                  | gender   | age_group      | population_group       |   median_income |   number_graduates |\n|---:|-------:|:-----------|:-------------------------------------------------------|:------------------------------------------------|:---------|:---------------|:-----------------------|----------------:|-------------------:|\n|  0 |   2014 | Alberta    | Career, technical or professional training certificate | Agriculture, natural resources and conservation | Man      | 15 to 34 years | Not a visible minority |           52800 |                 70 |\n|  1 |   2014 | Alberta    | Career, technical or professional training certificate | Agriculture, natural resources and conservation | Woman    | 15 to 34 years | Not a visible minority |           36600 |                100 |\n|  2 |   2014 | Alberta    | Career, technical or professional training certificate | Architecture, engineering, and related trades   | Man      | 15 to 34 years | Not a visible minority |           72300 |                460 |\n|  3 |   2014 | Alberta    | Career, technical or professional training certificate | Architecture, engineering, and related trades   | Man      | 15 to 34 years | South Asian            |           60200 |                 20 |\n|  4 |   2014 | Alberta    | Career, technical or professional training certificate | Architecture, engineering, and related trades   | Man      | 35 to 64 years | Not a visible minority |          103200 |                120 |\n:::\n:::\n\n\n:::\n\n#### 2. Exploratory Data Analysis\n\nBefore performing statistical inquiries or predictive modelling, it's helpful to perform exploratory data analysis to gain an understanding of how income varies by demographic and educational factors. \n\n**Median Income by Gender**\n\nThis visualization examines how median income varies by gender. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(income_data, aes(\n  y = gender, \n  x = median_income)) +\n  stat_halfeye(aes(weight = number_graduates), \n               adjust = 1.5, \n               justification = -0.1, \n               .width = 0, \n               point_colour = NA, \n               alpha = 0.6,\n               fill = \"darkgreen\") +\n  geom_boxplot(aes(weight = number_graduates), \n               width = 0.15, \n               outlier.shape = NA, \n               alpha = 0.7, \n               color = \"black\") +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  labs(\n    title = \"Median Income Distribution by Gender\",\n    y = \"Gender\",\n    x = \"Median Income ($)\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_1_r-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Expand the dataframe based on 'number_graduates' weight \nexpanded_data = income_data.loc[\n    np.repeat(income_data.index, income_data[\"number_graduates\"].astype(int))\n]\n\n# Set up the visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 5))\n\n\n# Draw the half-eye / distribution and boxplot components using the expanded data\nsns.violinplot(\n    data=expanded_data,\n    x=\"median_income\",\n    y=\"gender\",\n    order=[\"Woman\", \"Man\"],\n    split=True,\n    color=\"darkgreen\",\n    inner=\"box\",\n    alpha=0.6,\n    bw_adjust=2,\n    ax=ax,\n)\n\n# Format labels and axes\nax.set_title(\"Median Income Distribution by Gender\", fontsize=13, pad=12)\nax.set_ylabel(\"Gender\", fontsize=11)\nax.set_xlabel(\"Median Income ($)\", fontsize=11)\n\n# Format x-axis as currency\nformatter = ticker.StrMethodFormatter(\"${x:,.0f}\")\nax.xaxis.set_major_formatter(formatter)\n\n# Clean up grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_1_py-1.png){width=768}\n:::\n:::\n\n:::\n\nWe can see that the income distribution for men has a higher median value, and is less right-skewed than the distribution for women. This suggests that in our dataset, more men are making higher incomes than women. \n\n**Median Income by Population Group**\n\nThis visualization investigates the income distributions by population group, a proxy for ethnicity. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(income_data, aes(\n  y = fct_rev(fct_reorder(population_group, median_income, .fun = median, .na_rm = TRUE)), \n  x = median_income)) +\n  stat_halfeye(aes(weight = number_graduates), \n               adjust = 1.5, \n               justification = -0.1, \n               .width = 0, \n               point_colour = NA, \n               alpha = 0.6,\n               fill = \"darkgreen\") +\n  geom_boxplot(aes(weight = number_graduates), \n               width = 0.15, \n               outlier.shape = NA, \n               alpha = 0.7, \n               color = \"black\") +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  labs(\n    title = \"Median Income Distribution by Population Group\",\n    subtitle = \"Ordered by Median Income\",\n    y = \"Population Group\",\n    x = \"Median Income ($)\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in rq.fit.br(wx, wy, tau = tau, ...): Solution may be nonunique\nWarning in rq.fit.br(wx, wy, tau = tau, ...): Solution may be nonunique\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_2_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Set up the visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 7))\n\n# Compute order based on median income (ascending order)\ngroup_order = (\n    expanded_data.groupby(\"population_group\")[\"median_income\"]\n    .median()\n    .sort_values(ascending=True)\n    .index\n)\n\n# Draw the half-eye / distribution and boxplot components using the expanded data\nsns.violinplot(\n    data=expanded_data,\n    x=\"median_income\",\n    y=\"population_group\",\n    order = group_order,\n    split=True,\n    color=\"darkgreen\",\n    inner=\"box\",\n    alpha=0.6,\n    bw_adjust=2,\n    ax=ax,\n)\n\n# Format labels and axes\nax.set_title(\"Median Income Distribution by Population Group\", fontsize=13, pad=20, loc='left')\nax.text(\n    0.0, 1.02, \"Ordered by Median Income\", \n    transform=ax.transAxes, fontsize=10, color=\"gray\"\n)\nax.set_ylabel(\"Population Group\", fontsize=11)\nax.set_xlabel(\"Median Income ($)\", fontsize=11)\n\n# Format x-axis as currency\nformatter = ticker.StrMethodFormatter(\"${x:,.0f}\")\nax.xaxis.set_major_formatter(formatter)\n\n# Clean up grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_2_py-1.png){width=768}\n:::\n:::\n\n\n:::\n\nWe can see that there are some differences by population groups in our visualization. Notably, \"Visible minority, n.i.e.\", which stands for \"not included elsewhere\", aka minority groups that don't fall into one of the major categories, has the lowest median income. Similar groups with low median incomes include \"Latin American\", \"Black\", and \"Multiple visible minorities\". The groups with higher median incomes include \"Japanese\", \"Chinese\", and \"Korean\". \n\n**Median Income by Educational Qualification**\n\nThis visualization investigates the impact of the type of educational qualification or degree on the income distribution of graduates. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(income_data, aes(\n  y = fct_rev(fct_reorder(educational_qualification, median_income, .fun = median, .na_rm = TRUE)), \n  x = median_income)) +\n  stat_halfeye(aes(weight = number_graduates), \n               adjust = 1.5, \n               justification = -0.1, \n               .width = 0, \n               point_colour = NA, \n               alpha = 0.6,\n               fill = \"darkgreen\") +\n  geom_boxplot(aes(weight = number_graduates), \n               width = 0.15, \n               outlier.shape = NA, \n               alpha = 0.7, \n               color = \"black\") +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  scale_y_discrete(labels = scales::label_wrap(width = 35)) +\n  labs(\n    title = \"Median Income Distribution by Educational Qualification\",\n    subtitle = \"Ordered by Median Income\",\n    y = \"Educational Qualification\",\n    x = \"Median Income ($)\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_3_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Set up the visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 7))\n\n# Compute order based on median income (ascending order)\ngroup_order = (\n    expanded_data.groupby(\"educational_qualification\")[\"median_income\"]\n    .median()\n    .sort_values(ascending=True)\n    .index\n)\n\n# Draw the half-eye / distribution and boxplot components using the expanded data\nsns.violinplot(\n    data=expanded_data,\n    x=\"median_income\",\n    y=\"educational_qualification\",\n    order = group_order,\n    split=True,\n    color=\"darkgreen\",\n    inner=\"box\",\n    alpha=0.6,\n    bw_adjust=2,\n    ax=ax,\n)\n\n# Format labels and axes\ncurrent_labels = [textwrap.fill(label.get_text(), width=35) for label in ax.get_yticklabels()]\nax.set_yticklabels(current_labels)\n\nax.set_title(\"Median Income Distribution by Educational Qualification\", fontsize=13, pad=20, loc='left')\nax.text(\n    0.0, 1.02, \"Ordered by Median Income\", \n    transform=ax.transAxes, fontsize=10, color=\"gray\"\n)\n\nax.set_ylabel(\"Educational Qualification\", fontsize=11)\nax.set_xlabel(\"Median Income ($)\", fontsize=11)\n\n# Format x-axis as currency\nformatter = ticker.StrMethodFormatter(\"${x:,.0f}\")\nax.xaxis.set_major_formatter(formatter)\n\n# Clean up grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_3_py-1.png){width=768}\n:::\n:::\n\n\n:::\n\nWe can see that, as is expected, the more advanced educational qualifications appear to have higher median incomes, such as professional degrees or doctoral degrees. \n\n**Median Income by Field of Study**\n\nThis visualization investigates income distributions by different fields of study. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(income_data, aes(\n  y = fct_rev(fct_reorder(field_of_study, median_income, .fun = median, .na_rm = TRUE)), \n  x = median_income)) +\n  stat_halfeye(aes(weight = number_graduates), \n               adjust = 1.5, \n               justification = -0.1, \n               .width = 0, \n               point_colour = NA, \n               alpha = 0.6,\n               fill = \"darkgreen\") +\n  geom_boxplot(aes(weight = number_graduates), \n               width = 0.15, \n               outlier.shape = NA, \n               alpha = 0.7, \n               color = \"black\") +\n  scale_x_continuous(labels = scales::dollar_format()) +\n  scale_y_discrete(labels = scales::label_wrap(width = 35)) +\n  labs(\n    title = \"Median Income Distribution by Field of Study\",\n    subtitle = \"Ordered by Median Income\",\n    y = \"Field of Study\",\n    x = \"Median Income ($)\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"none\", panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_4_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Set up the visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 7))\n\n# Compute order based on median income (ascending order)\ngroup_order = (\n    expanded_data.groupby(\"field_of_study\")[\"median_income\"]\n    .median()\n    .sort_values(ascending=True)\n    .index\n)\n\n# Draw the half-eye / distribution and boxplot components using the expanded data\nsns.violinplot(\n    data=expanded_data,\n    x=\"median_income\",\n    y=\"field_of_study\",\n    order = group_order,\n    split=True,\n    color=\"darkgreen\",\n    inner=\"box\",\n    alpha=0.6,\n    bw_adjust=2,\n    ax=ax,\n)\n\n# Format labels and axes\ncurrent_labels = [textwrap.fill(label.get_text(), width=35) for label in ax.get_yticklabels()]\nax.set_yticklabels(current_labels)\n\nax.set_title(\"Median Income Distribution by Field of Study\", fontsize=13, pad=20, loc='left')\nax.text(\n    0.0, 1.02, \"Ordered by Median Income\", \n    transform=ax.transAxes, fontsize=10, color=\"gray\"\n)\n\nax.set_ylabel(\"Field of Study\", fontsize=11)\nax.set_xlabel(\"Median Income ($)\", fontsize=11)\n\n# Format x-axis as currency\nformatter = ticker.StrMethodFormatter(\"${x:,.0f}\")\nax.xaxis.set_major_formatter(formatter)\n\n# Clean up grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/eda_4_py-1.png){width=768}\n:::\n:::\n\n\n:::\n\nWe can see that the fields with the lowest median incomes are visual and performing arts, humanities, and transportation services, while the fields with the highest median incomes include math and computer sciences, health fields, and education. \n\n\n#### 3. Hypothesis Testing\n\nTo evaluate whether different demographics experience significantly different median incomes, we begin by investigating gender. \n\n::: {.callout-note appearance=\"simple\"}\n## Statistical Hypotheses (Gender)\n* **$H_0$ (Null):** The distributions of median income are identical across genders.\n* **$H_a$ (Alternative):** The distributions of median income are not identical across genders.\n:::\n\nBefore performing an ANOVA test, we must verify its underlying statistical assumptions:\n\n1. **Independence of Observations:**  \n   Because the dataset contains distinct aggregate rows per graduate subgroup with no repeated measures, the independence assumption is reasonably satisfied.\n\n2. **Normality of Residuals:**  \n   We examine the residuals using a Q-Q plot. If normality holds, the residual points should closely track the 45-degree reference line.\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_gender_model <- aov(median_income ~ gender, data = income_data)\nqqnorm(residuals(anova_gender_model))\nqqline(residuals(anova_gender_model), col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/qq_plot_r-3.png){width=672}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nanova_model = smf.ols(\"median_income ~ C(gender)\", data=income_data).fit()\nresiduals = anova_model.resid\nfig = sm.qqplot(residuals, line=\"45\", fit=True)\n\nplt.title(\"Normal Q-Q Plot of ANOVA Residuals\", fontsize=12)\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/qq_plot_py-1.png){width=672}\n:::\n:::\n\n:::\n\nAbove, we can see that the residuals are not normally distributed, as the points deviate from the red line on both extremes. \n\nWe can additionally test this normality by making a density plot of the residuals, and visually inspecting the shape of the curve. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(resids = residuals(anova_gender_model)), aes(x = resids)) +\n  geom_density(fill = \"#7EA8F8\", alpha = 0.6) +\n  labs(\n    title = \"Density Plot of ANOVA Residuals\",\n    x = \"Residuals\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/residuals_r-3.png){width=672}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nresid_df = pd.DataFrame({\"resids\": residuals})\n\n# Set visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 5), layout=\"constrained\")\n\n# Create the density plot (equivalent to geom_density)\nsns.kdeplot(\n    data=resid_df,\n    x=\"resids\",\n    fill=True,\n    color=\"#7EA8F8\",\n    alpha=0.6,\n    ax=ax,\n)\n\n# Format titles and labels (Left-aligned title)\nax.set_title(\"Density Plot of ANOVA Residuals\", fontsize=13, pad=15, loc=\"left\")\nax.set_xlabel(\"Residuals\", fontsize=11)\nax.set_ylabel(\"Density\", fontsize=11)\n\n# Clean grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/residuals_py-1.png){width=768}\n:::\n:::\n\n:::\n\nWe can see that the residuals are not normally distributed above, but instead are right-skewed. This is typical in income datasets, as most people have a low to moderate income, while a small number of people earn very high amounts, as discussed in [Passion Driven Statistics](https://alanarnholt.github.io/PDS-Bookdown2/skewed-right-distributions.html). \n\n3. **Homogeneity of Variances - Levene's test**\n    For ANOVA, we also need to check if the different groups have comparable amounts of variance. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(median_income ~ gender, data = income_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n         Df F value    Pr(>F)    \ngroup     1  19.612 9.545e-06 ***\n      16634                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Group the median_income values by the categories in 'gender'\n# We use a list comprehension to pass each group's data as a separate argument to stats.levene\ngroups = [group[\"median_income\"].values for _, group in income_data.groupby(\"gender\")]\n\n# Run Levene's test (using the default median-based center)\nlevene_result = stats.levene(*groups, center=\"median\")\n\nprint(f\"Statistic: {levene_result.statistic:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistic: 19.6124\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"p-value: {levene_result.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.0000\n```\n\n\n:::\n:::\n\n\n:::\n\nWe can see that the variances are not homogeneous in our datset, as the p-value from the Levene's test is smaller than 0.05. \n\nSince the residuals are not normally distributed and the variances are not homogeneous, we cannot use an ANOVA test. Instead, we will use a non-parametric Kruskal-Wallis test. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(median_income ~ gender, data = income_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  median_income by gender\nKruskal-Wallis chi-squared = 249.95, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nkruskal_result = stats.kruskal(*groups)\n\nprint(f\"H-statistic: {kruskal_result.statistic:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH-statistic: 249.9473\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"p-value: {kruskal_result.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.0000\n```\n\n\n:::\n:::\n\n\n:::\n\nSince p-value is smaller than 0.05, we can reject the null hypothesis in favor of the alternative, and conclude that there is statistical evidence for a difference in median income between men and women in our dataset. \n\n**Hypothesis Testing: Population Group**\n\nFollowing the same analytical framework, we evaluate whether median incomes differ significantly across population groups. \n\n::: {.callout-note appearance=\"simple\"}\n## Statistical Hypotheses (Population Group)\n* **$H_0$ (Null):** The distributions of median income are identical across all population groups.\n* **$H_a$ (Alternative):** The distributions of median income are not identical across all population groups.\n:::\n\nNext, we verify the underlying assumptions for our test:\n\n1. **Independence of Observations:**  \n   Because the dataset contains distinct aggregate rows per graduate subgroup with no repeated measures, the independence assumption remains satisfied.\n\n2. **Normality of Residuals:**  \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_popgroup_model <- aov(median_income ~ population_group, data = income_data)\nqqnorm(residuals(anova_popgroup_model))\nqqline(residuals(anova_popgroup_model), col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/qq_plot_popgroup_r-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nanova_popgroup_model = smf.ols(\"median_income ~ C(population_group)\", data=income_data).fit()\nresiduals_popgroup = anova_popgroup_model.resid\nfig = sm.qqplot(residuals_popgroup, line=\"45\", fit=True)\n\nplt.title(\"Normal Q-Q Plot of ANOVA Residuals\", fontsize=12)\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/qq_plot_popgroup_py-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(resids = residuals(anova_popgroup_model)), aes(x = resids)) +\n  geom_density(fill = \"#7EA8F8\", alpha = 0.6) +\n  labs(\n    title = \"Density Plot of ANOVA Residuals\",\n    x = \"Residuals\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/residuals_popgroup_r-3.png){width=672}\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nresid_popgroup_df = pd.DataFrame({\"resids\": residuals_popgroup})\n\n# Set visual style\nsns.set_theme(style=\"whitegrid\")\nfig, ax = plt.subplots(figsize=(8, 5), layout=\"constrained\")\n\n# Create the density plot (equivalent to geom_density)\nsns.kdeplot(\n    data=resid_popgroup_df,\n    x=\"resids\",\n    fill=True,\n    color=\"#7EA8F8\",\n    alpha=0.6,\n    ax=ax,\n)\n\n# Format titles and labels (Left-aligned title)\nax.set_title(\"Density Plot of ANOVA Residuals\", fontsize=13, pad=15, loc=\"left\")\nax.set_xlabel(\"Residuals\", fontsize=11)\nax.set_ylabel(\"Density\", fontsize=11)\n\n# Clean grid lines\nax.grid(True, which=\"major\", alpha=0.5)\nax.grid(False, which=\"minor\")\n\nplt.show()\n```\n\n::: {.cell-output-display}\n![](postgradincome_files/figure-html/residuals_popgroup_py-1.png){width=768}\n:::\n:::\n\n\n:::\n\nAgain, from both the Q-Q plot and the residuals density plot, we can see that the residuals are not normally distributed. \n\n3. **Homogeneity of Variances - Levene's test**\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(median_income ~ population_group, data = income_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n         Df F value    Pr(>F)    \ngroup    12  33.816 < 2.2e-16 ***\n      16623                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Group the median_income values by the categories in 'population_group'\n# We use a list comprehension to pass each group's data as a separate argument to stats.levene\ngroups_pop = [group[\"median_income\"].values for _, group in income_data.groupby(\"population_group\")]\n\n# Run Levene's test (using the default median-based center)\nlevene_result_pop = stats.levene(*groups_pop, center=\"median\")\n\nprint(f\"Statistic: {levene_result_pop.statistic:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistic: 33.8160\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"p-value: {levene_result_pop.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.0000\n```\n\n\n:::\n:::\n\n\n:::\n\nSimilarly, since the p-value is less than 0.05, we can conclude that the variances are heterogeneous, and this assumption is violated. \n\nTherefore, since the residuals are not normally distributed and the variances are not homogeneous, we cannot use ANOVA and instead will use a Kruskal-Wallis test. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(median_income ~ population_group, data = income_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  median_income by population_group\nKruskal-Wallis chi-squared = 441.45, df = 12, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\nkruskal_result_pop = stats.kruskal(*groups_pop)\n\nprint(f\"H-statistic: {kruskal_result_pop.statistic:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH-statistic: 441.4463\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"p-value: {kruskal_result_pop.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.0000\n```\n\n\n:::\n:::\n\n\n:::\n\nSince p-value is smaller than 0.05, we can reject the null hypothesis in favor of the alternative, that the distributions of median income are not identical across all population groups. To find out which groups differ, we need to conduct a Dunn's Post-Hoc test with a Bonferroni correction for multiple comparisons. \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run Dunn's test with Bonferroni correction\ndunnTest(median_income ~ population_group, data = income_data, method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  Kruskal-Wallis rank sum test\n\ndata: x and g\nKruskal-Wallis chi-squared = 441.4463, df = 12, p-value = 0\n\n                      Dunn's Pairwise Comparison of x by g                      \n                                  (Bonferroni)                                  \n\nCol Mean-│\nRow Mean │       Arab      Black    Chinese   Filipino   Japanese     Korean\n─────────┼──────────────────────────────────────────────────────────────────\n   Black │   1.075043\n         │     1.0000 \n         │\n Chinese │  -4.179848  -6.352509\n         │     0.0023*    0.0000*\n         │\nFilipino │   3.966620   3.457290   9.008395\n         │     0.0057*    0.0426*    0.0000*\n         │\nJapanese │  -1.502771  -1.714895  -0.727517  -2.333302\n         │     1.0000     1.0000     1.0000     1.0000 \n         │\n  Korean │  -1.702668  -2.489163   0.829061  -4.402021   0.943508\n         │     1.0000     0.9987     1.0000     0.0008*    1.0000 \n         │\nLatin Am │   5.398594   5.063674   9.873877   1.899024   2.749017   5.491655\n         │     0.0000*    0.0000*    0.0000*    1.0000     0.4662     0.0000*\n         │\nMultiple │   2.795629   2.227518   6.090442  -0.192745   2.243680   3.645668\n         │     0.4040     1.0000     0.0000*    1.0000     1.0000     0.0208*\n         │\nNot a vi │  -5.701684  -9.274843  -1.066412  -11.63516   0.606254  -1.323645\n         │     0.0000*    0.0000*    1.0000     0.0000*    1.0000     1.0000 \n         │\nSouth As │  -1.698926  -3.372017   3.070749  -6.435489   1.194381   0.744825\n         │     1.0000     0.0582     0.1665     0.0000*    1.0000     1.0000 \n         │\nSoutheas │   0.835576   0.063859   4.199237  -2.386338   1.702492   2.170446\n         │     1.0000     1.0000     0.0021*    1.0000     1.0000     1.0000 \n         │\nVisible  │   4.817782   4.458149   7.121569   2.702420   3.202361   5.337825\n         │     0.0001*    0.0006*    0.0000*    0.5369     0.1063     0.0000*\n         │\nWest Asi │   2.093965   1.455992   5.433813  -0.988740   2.041433   3.110133\n         │     1.0000     1.0000     0.0000*    1.0000     1.0000     0.1459 \nCol Mean-│\nRow Mean │   Latin Am   Multiple   Not a vi   South As   Southeas   Visible \n─────────┼──────────────────────────────────────────────────────────────────\nMultiple │  -1.658353\n         │     1.0000 \n         │\nNot a vi │  -11.91891  -7.126342\n         │     0.0000*    0.0000*\n         │\nSouth As │  -7.649699  -4.281610   5.126390\n         │     0.0000*    0.0014*    0.0000*\n         │\nSoutheas │  -3.771738  -1.774095   5.185605   2.251838\n         │     0.0126*    1.0000     0.0000*    1.0000 \n         │\nVisible  │   1.522750   2.562213   7.732767   5.875727   3.973969\n         │     1.0000     0.8113     0.0000*    0.0000*    0.0055*\n         │\nWest Asi │  -2.433761  -0.650850   6.466451   3.567683   1.129752  -3.089427\n         │     1.0000     1.0000     0.0000*    0.0281*    1.0000     0.1564 \n\nFWER = 0.05\nReject Ho if adjusted p ≤ FWER, where (unadjusted) p = Pr(|Z| ≥ |z|)\nDunn (1964) Kruskal-Wallis multiple comparison\n\n  p-values adjusted with the Bonferroni method.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                               Comparison            Z\n1                                            Arab - Black   1.07504310\n2                                          Arab - Chinese  -4.17984839\n3                                         Black - Chinese  -6.35250976\n4                                         Arab - Filipino   3.96662098\n5                                        Black - Filipino   3.45729010\n6                                      Chinese - Filipino   9.00839505\n7                                         Arab - Japanese  -1.50277101\n8                                        Black - Japanese  -1.71489523\n9                                      Chinese - Japanese  -0.72751710\n10                                    Filipino - Japanese  -2.33330275\n11                                          Arab - Korean  -1.70266866\n12                                         Black - Korean  -2.48916310\n13                                       Chinese - Korean   0.82906119\n14                                      Filipino - Korean  -4.40202141\n15                                      Japanese - Korean   0.94350803\n16                                  Arab - Latin American   5.39859477\n17                                 Black - Latin American   5.06367492\n18                               Chinese - Latin American   9.87387758\n19                              Filipino - Latin American   1.89902432\n20                              Japanese - Latin American   2.74901726\n21                                Korean - Latin American   5.49165566\n22                     Arab - Multiple visible minorities   2.79562932\n23                    Black - Multiple visible minorities   2.22751858\n24                  Chinese - Multiple visible minorities   6.09044206\n25                 Filipino - Multiple visible minorities  -0.19274488\n26                 Japanese - Multiple visible minorities   2.24368043\n27                   Korean - Multiple visible minorities   3.64566855\n28           Latin American - Multiple visible minorities  -1.65835360\n29                          Arab - Not a visible minority  -5.70168471\n30                         Black - Not a visible minority  -9.27484356\n31                       Chinese - Not a visible minority  -1.06641231\n32                      Filipino - Not a visible minority -11.63516089\n33                      Japanese - Not a visible minority   0.60625425\n34                        Korean - Not a visible minority  -1.32364521\n35                Latin American - Not a visible minority -11.91891181\n36   Multiple visible minorities - Not a visible minority  -7.12634237\n37                                     Arab - South Asian  -1.69892654\n38                                    Black - South Asian  -3.37201768\n39                                  Chinese - South Asian   3.07074910\n40                                 Filipino - South Asian  -6.43548974\n41                                 Japanese - South Asian   1.19438122\n42                                   Korean - South Asian   0.74482525\n43                           Latin American - South Asian  -7.64969953\n44              Multiple visible minorities - South Asian  -4.28161091\n45                   Not a visible minority - South Asian   5.12639065\n46                                 Arab - Southeast Asian   0.83557620\n47                                Black - Southeast Asian   0.06385869\n48                              Chinese - Southeast Asian   4.19923783\n49                             Filipino - Southeast Asian  -2.38633823\n50                             Japanese - Southeast Asian   1.70249260\n51                               Korean - Southeast Asian   2.17044606\n52                       Latin American - Southeast Asian  -3.77173808\n53          Multiple visible minorities - Southeast Asian  -1.77409535\n54               Not a visible minority - Southeast Asian   5.18560574\n55                          South Asian - Southeast Asian   2.25183887\n56                        Arab - Visible minority, n.i.e.   4.81778259\n57                       Black - Visible minority, n.i.e.   4.45814949\n58                     Chinese - Visible minority, n.i.e.   7.12156990\n59                    Filipino - Visible minority, n.i.e.   2.70242025\n60                    Japanese - Visible minority, n.i.e.   3.20236159\n61                      Korean - Visible minority, n.i.e.   5.33782591\n62              Latin American - Visible minority, n.i.e.   1.52275048\n63 Multiple visible minorities - Visible minority, n.i.e.   2.56221305\n64      Not a visible minority - Visible minority, n.i.e.   7.73276722\n65                 South Asian - Visible minority, n.i.e.   5.87572717\n66             Southeast Asian - Visible minority, n.i.e.   3.97396984\n67                                      Arab - West Asian   2.09396560\n68                                     Black - West Asian   1.45599270\n69                                   Chinese - West Asian   5.43381397\n70                                  Filipino - West Asian  -0.98874023\n71                                  Japanese - West Asian   2.04143336\n72                                    Korean - West Asian   3.11013307\n73                            Latin American - West Asian  -2.43376154\n74               Multiple visible minorities - West Asian  -0.65085037\n75                    Not a visible minority - West Asian   6.46645118\n76                               South Asian - West Asian   3.56768386\n77                           Southeast Asian - West Asian   1.12975219\n78                  Visible minority, n.i.e. - West Asian  -3.08942732\n        P.unadj        P.adj\n1  2.823554e-01 1.000000e+00\n2  2.917035e-05 2.275287e-03\n3  2.118300e-10 1.652274e-08\n4  7.289878e-05 5.686105e-03\n5  5.456371e-04 4.255970e-02\n6  2.090939e-19 1.630933e-17\n7  1.328981e-01 1.000000e+00\n8  8.636444e-02 1.000000e+00\n9  4.669092e-01 1.000000e+00\n10 1.963226e-02 1.000000e+00\n11 8.863009e-02 1.000000e+00\n12 1.280442e-02 9.987448e-01\n13 4.070698e-01 1.000000e+00\n14 1.072470e-05 8.365264e-04\n15 3.454211e-01 1.000000e+00\n16 6.716489e-08 5.238861e-06\n17 4.112507e-07 3.207755e-05\n18 5.403449e-23 4.214690e-21\n19 5.756128e-02 1.000000e+00\n20 5.977424e-03 4.662391e-01\n21 3.981831e-08 3.105829e-06\n22 5.179877e-03 4.040304e-01\n23 2.591264e-02 1.000000e+00\n24 1.125993e-09 8.782748e-08\n25 8.471588e-01 1.000000e+00\n26 2.485297e-02 1.000000e+00\n27 2.666975e-04 2.080241e-02\n28 9.724612e-02 1.000000e+00\n29 1.186291e-08 9.253069e-07\n30 1.778799e-20 1.387463e-18\n31 2.862373e-01 1.000000e+00\n32 2.730747e-31 2.129983e-29\n33 5.443459e-01 1.000000e+00\n34 1.856209e-01 1.000000e+00\n35 9.433257e-33 7.357941e-31\n36 1.030712e-12 8.039550e-11\n37 8.933303e-02 1.000000e+00\n38 7.461966e-04 5.820333e-02\n39 2.135225e-03 1.665475e-01\n40 1.230758e-10 9.599916e-09\n41 2.323289e-01 1.000000e+00\n42 4.563774e-01 1.000000e+00\n43 2.014495e-14 1.571306e-12\n44 1.855452e-05 1.447253e-03\n45 2.953495e-07 2.303726e-05\n46 4.033934e-01 1.000000e+00\n47 9.490827e-01 1.000000e+00\n48 2.678149e-05 2.088956e-03\n49 1.701709e-02 1.000000e+00\n50 8.866306e-02 1.000000e+00\n51 2.997307e-02 1.000000e+00\n52 1.621144e-04 1.264492e-02\n53 7.604738e-02 1.000000e+00\n54 2.153139e-07 1.679448e-05\n55 2.433246e-02 1.000000e+00\n56 1.451624e-06 1.132267e-04\n57 8.267024e-06 6.448279e-04\n58 1.067046e-12 8.322958e-11\n59 6.883670e-03 5.369262e-01\n60 1.363058e-03 1.063185e-01\n61 9.406771e-08 7.337281e-06\n62 1.278211e-01 1.000000e+00\n63 1.040075e-02 8.112585e-01\n64 1.052336e-14 8.208222e-13\n65 4.209912e-09 3.283731e-07\n66 7.068452e-05 5.513392e-03\n67 3.626304e-02 1.000000e+00\n68 1.453946e-01 1.000000e+00\n69 5.516209e-08 4.302643e-06\n70 3.227903e-01 1.000000e+00\n71 4.120777e-02 1.000000e+00\n72 1.870031e-03 1.458624e-01\n73 1.494284e-02 1.000000e+00\n74 5.151431e-01 1.000000e+00\n75 1.003312e-10 7.825835e-09\n76 3.601507e-04 2.809175e-02\n77 2.585807e-01 1.000000e+00\n78 2.005428e-03 1.564234e-01\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\ndunn_results = sp.posthoc_dunn(\n    expanded_data, \n    val_col=\"median_income\", \n    group_col=\"population_group\", \n    p_adjust=\"bonferroni\"\n)\n\nprint(dunn_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      Arab  ...     West Asian\nArab                          1.000000e+00  ...   5.798177e-86\nBlack                         0.000000e+00  ...   6.098350e-03\nChinese                       0.000000e+00  ...   0.000000e+00\nFilipino                     5.033313e-153  ...   1.000000e+00\nJapanese                      7.019583e-29  ...   7.747430e-52\nKorean                        1.884370e-59  ...  4.386880e-179\nLatin American                0.000000e+00  ...   2.160423e-53\nMultiple visible minorities   2.488548e-90  ...   1.000000e+00\nNot a visible minority       4.358251e-176  ...   0.000000e+00\nSouth Asian                  6.274158e-104  ...  3.780196e-290\nSoutheast Asian               3.673739e-03  ...   3.130330e-87\nVisible minority, n.i.e.     1.997255e-224  ...   4.165221e-60\nWest Asian                    5.798177e-86  ...   1.000000e+00\n\n[13 rows x 13 columns]\n```\n\n\n:::\n:::\n\n\n:::\n\nFrom both the Kruskal-Wallis and the Dunn's Post-Hoc test, we can see that there are statistically significant differences in median income distributions between different population groups. Notable differences appear around comparing \"Not a visible minority\" to many groups, including \"Arab\", \"Black\", \"Latin American\", etc. \n\n\n#### 4. Predictive Model\n\nTo understand the factors driving median income and identify variations across groups, we will build a linear regression model. Because our dataset is aggregated, where each row represents a group of individuals rather than a single person, we need to use the number of individuals contained in the `number_graduates` column as the weight of each row in data splitting as well as model training and evaluation. \n\nOur modeling workflow is structured as follows:\n\n* **Data Splitting:** We partition the weighted dataset into training and test sets to ensure unbiased evaluation.\n* **Coefficient & Group Analysis:** We examine the model's learned coefficients and their statistical significance to uncover key drivers and differences between groups.\n* **Performance Evaluation:** We assess model generalizability by calculating the root mean squared error (RMSE) of our predictions on the test set.\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Split dataset to train and test sets using stratified splitting\n# Ensures small and large weight rows are evenly distributed between train and test\ndata_split <- initial_split(income_data, prop = 0.8, strata = number_graduates)\n\n# Create the training and testing sets\nincome_train_weighted <- training(data_split)\nincome_test_weighted  <- testing(data_split)\n```\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n\nnp.random.seed(42)\n\n# Bin the continuous 'number_graduates' column into discrete strata \n# (Stratified splitting in scikit-learn requires categorical bins)\nincome_data[\"graduate_strata\"] = pd.qcut(\n    income_data[\"number_graduates\"], q=5, labels=False, duplicates=\"drop\"\n)\n\n# Perform an 80/20 stratified split \nincome_train_weighted, income_test_weighted = train_test_split(\n    income_data,\n    test_size=0.2,\n    stratify=income_data[\"graduate_strata\"],\n    random_state=42,\n)\n\n# Optional: Drop the temporary strata column if you no longer need it\n#income_train_weighted = income_train_weighted.drop(columns=[\"graduate_strata\"])\n#income_test_weighted = income_test_weighted.drop(columns=[\"graduate_strata\"])\n```\n:::\n\n:::\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a weighted linear model\nmodel_lm_weighted <- lm(median_income ~ educational_qualification + population_group + gender + field_of_study, \n               data = income_train_weighted,\n               weights = number_graduates)\n\n# View coefficients and summary\nsummary(model_lm_weighted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = median_income ~ educational_qualification + population_group + \n    gender + field_of_study, data = income_train_weighted, weights = number_graduates)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-946955  -66975    2198   76670 1414478 \n\nCoefficients:\n                                                                                              Estimate\n(Intercept)                                                                                   31044.48\neducational_qualificationCareer, technical or professional training diploma                    8843.98\neducational_qualificationCareer, technical or professional training short credential          14744.61\neducational_qualificationDoctoral degree                                                      54592.08\neducational_qualificationMaster's degree                                                      47391.53\neducational_qualificationMaster's diploma                                                     43709.51\neducational_qualificationPost career, technical or professional training program certificate  25097.39\neducational_qualificationPost-baccalaureate non-graduate diploma                              52519.28\neducational_qualificationProfessional degree                                                  56240.06\neducational_qualificationUndergraduate certificate                                            25890.24\neducational_qualificationUndergraduate degree                                                 24269.59\npopulation_groupBlack                                                                          1927.43\npopulation_groupChinese                                                                        5865.26\npopulation_groupFilipino                                                                       4942.82\npopulation_groupJapanese                                                                       9713.96\npopulation_groupKorean                                                                         5789.46\npopulation_groupLatin American                                                                 2277.43\npopulation_groupMultiple visible minorities                                                    1575.76\npopulation_groupNot a visible minority                                                         7136.39\npopulation_groupSouth Asian                                                                    4263.29\npopulation_groupSoutheast Asian                                                                3235.09\npopulation_groupVisible minority, n.i.e.                                                        -32.28\npopulation_groupWest Asian                                                                    -1135.69\ngenderWoman                                                                                   -4883.60\nfield_of_studyArchitecture, engineering, and related trades                                   12101.84\nfield_of_studyBusiness, management and public administration                                   5555.85\nfield_of_studyEducation                                                                        5750.37\nfield_of_studyHealth and related fields                                                       14448.37\nfield_of_studyHumanities                                                                     -16248.70\nfield_of_studyMathematics, computer and information sciences                                  11357.02\nfield_of_studyOther instructional programs                                                     1304.71\nfield_of_studyPersonal, protective and transportation services                                 5115.95\nfield_of_studyPhysical and life sciences and technologies                                    -12320.45\nfield_of_studySocial and behavioural sciences and law                                         -6596.22\nfield_of_studyVisual and performing arts, and communications technologies                    -17637.22\n                                                                                             Std. Error\n(Intercept)                                                                                     1151.84\neducational_qualificationCareer, technical or professional training diploma                      393.58\neducational_qualificationCareer, technical or professional training short credential             642.48\neducational_qualificationDoctoral degree                                                        1219.72\neducational_qualificationMaster's degree                                                         479.81\neducational_qualificationMaster's diploma                                                       1058.11\neducational_qualificationPost career, technical or professional training program certificate     762.65\neducational_qualificationPost-baccalaureate non-graduate diploma                                1957.48\neducational_qualificationProfessional degree                                                     822.83\neducational_qualificationUndergraduate certificate                                               648.12\neducational_qualificationUndergraduate degree                                                    383.63\npopulation_groupBlack                                                                            961.02\npopulation_groupChinese                                                                          935.96\npopulation_groupFilipino                                                                        1103.21\npopulation_groupJapanese                                                                        7389.56\npopulation_groupKorean                                                                          1876.56\npopulation_groupLatin American                                                                  1313.02\npopulation_groupMultiple visible minorities                                                     1549.85\npopulation_groupNot a visible minority                                                           831.09\npopulation_groupSouth Asian                                                                      917.07\npopulation_groupSoutheast Asian                                                                 1540.16\npopulation_groupVisible minority, n.i.e.                                                        2178.71\npopulation_groupWest Asian                                                                      1542.08\ngenderWoman                                                                                      234.54\nfield_of_studyArchitecture, engineering, and related trades                                      769.46\nfield_of_studyBusiness, management and public administration                                     738.56\nfield_of_studyEducation                                                                          809.70\nfield_of_studyHealth and related fields                                                          746.59\nfield_of_studyHumanities                                                                         899.64\nfield_of_studyMathematics, computer and information sciences                                     917.93\nfield_of_studyOther instructional programs                                                      1773.44\nfield_of_studyPersonal, protective and transportation services                                   876.24\nfield_of_studyPhysical and life sciences and technologies                                        923.24\nfield_of_studySocial and behavioural sciences and law                                            749.43\nfield_of_studyVisual and performing arts, and communications technologies                        877.61\n                                                                                             t value\n(Intercept)                                                                                   26.952\neducational_qualificationCareer, technical or professional training diploma                   22.471\neducational_qualificationCareer, technical or professional training short credential          22.950\neducational_qualificationDoctoral degree                                                      44.758\neducational_qualificationMaster's degree                                                      98.771\neducational_qualificationMaster's diploma                                                     41.309\neducational_qualificationPost career, technical or professional training program certificate  32.908\neducational_qualificationPost-baccalaureate non-graduate diploma                              26.830\neducational_qualificationProfessional degree                                                  68.349\neducational_qualificationUndergraduate certificate                                            39.946\neducational_qualificationUndergraduate degree                                                 63.263\npopulation_groupBlack                                                                          2.006\npopulation_groupChinese                                                                        6.267\npopulation_groupFilipino                                                                       4.480\npopulation_groupJapanese                                                                       1.315\npopulation_groupKorean                                                                         3.085\npopulation_groupLatin American                                                                 1.734\npopulation_groupMultiple visible minorities                                                    1.017\npopulation_groupNot a visible minority                                                         8.587\npopulation_groupSouth Asian                                                                    4.649\npopulation_groupSoutheast Asian                                                                2.100\npopulation_groupVisible minority, n.i.e.                                                      -0.015\npopulation_groupWest Asian                                                                    -0.736\ngenderWoman                                                                                  -20.822\nfield_of_studyArchitecture, engineering, and related trades                                   15.728\nfield_of_studyBusiness, management and public administration                                   7.523\nfield_of_studyEducation                                                                        7.102\nfield_of_studyHealth and related fields                                                       19.353\nfield_of_studyHumanities                                                                     -18.061\nfield_of_studyMathematics, computer and information sciences                                  12.372\nfield_of_studyOther instructional programs                                                     0.736\nfield_of_studyPersonal, protective and transportation services                                 5.838\nfield_of_studyPhysical and life sciences and technologies                                    -13.345\nfield_of_studySocial and behavioural sciences and law                                         -8.802\nfield_of_studyVisual and performing arts, and communications technologies                    -20.097\n                                                                                             Pr(>|t|)\n(Intercept)                                                                                   < 2e-16\neducational_qualificationCareer, technical or professional training diploma                   < 2e-16\neducational_qualificationCareer, technical or professional training short credential          < 2e-16\neducational_qualificationDoctoral degree                                                      < 2e-16\neducational_qualificationMaster's degree                                                      < 2e-16\neducational_qualificationMaster's diploma                                                     < 2e-16\neducational_qualificationPost career, technical or professional training program certificate  < 2e-16\neducational_qualificationPost-baccalaureate non-graduate diploma                              < 2e-16\neducational_qualificationProfessional degree                                                  < 2e-16\neducational_qualificationUndergraduate certificate                                            < 2e-16\neducational_qualificationUndergraduate degree                                                 < 2e-16\npopulation_groupBlack                                                                         0.04492\npopulation_groupChinese                                                                      3.80e-10\npopulation_groupFilipino                                                                     7.51e-06\npopulation_groupJapanese                                                                      0.18868\npopulation_groupKorean                                                                        0.00204\npopulation_groupLatin American                                                                0.08285\npopulation_groupMultiple visible minorities                                                   0.30930\npopulation_groupNot a visible minority                                                        < 2e-16\npopulation_groupSouth Asian                                                                  3.37e-06\npopulation_groupSoutheast Asian                                                               0.03571\npopulation_groupVisible minority, n.i.e.                                                      0.98818\npopulation_groupWest Asian                                                                    0.46146\ngenderWoman                                                                                   < 2e-16\nfield_of_studyArchitecture, engineering, and related trades                                   < 2e-16\nfield_of_studyBusiness, management and public administration                                 5.72e-14\nfield_of_studyEducation                                                                      1.29e-12\nfield_of_studyHealth and related fields                                                       < 2e-16\nfield_of_studyHumanities                                                                      < 2e-16\nfield_of_studyMathematics, computer and information sciences                                  < 2e-16\nfield_of_studyOther instructional programs                                                    0.46193\nfield_of_studyPersonal, protective and transportation services                               5.39e-09\nfield_of_studyPhysical and life sciences and technologies                                     < 2e-16\nfield_of_studySocial and behavioural sciences and law                                         < 2e-16\nfield_of_studyVisual and performing arts, and communications technologies                     < 2e-16\n                                                                                                \n(Intercept)                                                                                  ***\neducational_qualificationCareer, technical or professional training diploma                  ***\neducational_qualificationCareer, technical or professional training short credential         ***\neducational_qualificationDoctoral degree                                                     ***\neducational_qualificationMaster's degree                                                     ***\neducational_qualificationMaster's diploma                                                    ***\neducational_qualificationPost career, technical or professional training program certificate ***\neducational_qualificationPost-baccalaureate non-graduate diploma                             ***\neducational_qualificationProfessional degree                                                 ***\neducational_qualificationUndergraduate certificate                                           ***\neducational_qualificationUndergraduate degree                                                ***\npopulation_groupBlack                                                                        *  \npopulation_groupChinese                                                                      ***\npopulation_groupFilipino                                                                     ***\npopulation_groupJapanese                                                                        \npopulation_groupKorean                                                                       ** \npopulation_groupLatin American                                                               .  \npopulation_groupMultiple visible minorities                                                     \npopulation_groupNot a visible minority                                                       ***\npopulation_groupSouth Asian                                                                  ***\npopulation_groupSoutheast Asian                                                              *  \npopulation_groupVisible minority, n.i.e.                                                        \npopulation_groupWest Asian                                                                      \ngenderWoman                                                                                  ***\nfield_of_studyArchitecture, engineering, and related trades                                  ***\nfield_of_studyBusiness, management and public administration                                 ***\nfield_of_studyEducation                                                                      ***\nfield_of_studyHealth and related fields                                                      ***\nfield_of_studyHumanities                                                                     ***\nfield_of_studyMathematics, computer and information sciences                                 ***\nfield_of_studyOther instructional programs                                                      \nfield_of_studyPersonal, protective and transportation services                               ***\nfield_of_studyPhysical and life sciences and technologies                                    ***\nfield_of_studySocial and behavioural sciences and law                                        ***\nfield_of_studyVisual and performing arts, and communications technologies                    ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 146800 on 13272 degrees of freedom\nMultiple R-squared:   0.65,\tAdjusted R-squared:  0.6491 \nF-statistic: 724.8 on 34 and 13272 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Fit the weighted linear model using statsmodels formula interface (WLS)\n# statsmodels automatically handles categorical columns (factors) using formula syntax\nmodel_lm_weighted = smf.wls(\n    formula=\"median_income ~ educational_qualification + population_group + gender + field_of_study\",\n    data=income_train_weighted,\n    weights=income_train_weighted[\"number_graduates\"]\n).fit()\n\n# View coefficients and summary\nprint(model_lm_weighted.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            WLS Regression Results                            \n==============================================================================\nDep. Variable:          median_income   R-squared:                       0.649\nModel:                            WLS   Adj. R-squared:                  0.648\nMethod:                 Least Squares   F-statistic:                     721.9\nDate:                Tue, 15 Sep 2026   Prob (F-statistic):               0.00\nTime:                        10:54:36   Log-Likelihood:            -1.4889e+05\nNo. Observations:               13308   AIC:                         2.979e+05\nDf Residuals:                   13273   BIC:                         2.981e+05\nDf Model:                          34                                         \nCovariance Type:            nonrobust                                         \n====================================================================================================================================================================\n                                                                                                       coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------------------------------------------------------------------------------------\nIntercept                                                                                         3.142e+04   1151.161     27.293      0.000    2.92e+04    3.37e+04\neducational_qualification[T.Career, technical or professional training diploma]                   8241.0774    409.763     20.112      0.000    7437.883    9044.272\neducational_qualification[T.Career, technical or professional training short credential]           1.47e+04    655.404     22.428      0.000    1.34e+04     1.6e+04\neducational_qualification[T.Doctoral degree]                                                      5.479e+04   1242.771     44.088      0.000    5.24e+04    5.72e+04\neducational_qualification[T.Master's degree]                                                      4.741e+04    488.690     97.016      0.000    4.65e+04    4.84e+04\neducational_qualification[T.Master's diploma]                                                      4.34e+04   1103.261     39.342      0.000    4.12e+04    4.56e+04\neducational_qualification[T.Post career, technical or professional training program certificate]  2.529e+04    776.618     32.568      0.000    2.38e+04    2.68e+04\neducational_qualification[T.Post-baccalaureate non-graduate diploma]                              5.631e+04   2089.349     26.953      0.000    5.22e+04    6.04e+04\neducational_qualification[T.Professional degree]                                                  5.635e+04    820.401     68.689      0.000    5.47e+04     5.8e+04\neducational_qualification[T.Undergraduate certificate]                                            2.494e+04    673.503     37.037      0.000    2.36e+04    2.63e+04\neducational_qualification[T.Undergraduate degree]                                                 2.382e+04    394.604     60.362      0.000     2.3e+04    2.46e+04\npopulation_group[T.Black]                                                                         1891.1901    963.501      1.963      0.050       2.590    3779.791\npopulation_group[T.Chinese]                                                                       5683.1673    940.107      6.045      0.000    3840.424    7525.911\npopulation_group[T.Filipino]                                                                      5157.3498   1104.645      4.669      0.000    2992.088    7322.611\npopulation_group[T.Japanese]                                                                      8406.3853   7797.149      1.078      0.281   -6877.140    2.37e+04\npopulation_group[T.Korean]                                                                        5443.0144   1945.455      2.798      0.005    1629.645    9256.383\npopulation_group[T.Latin American]                                                                2022.2688   1337.414      1.512      0.131    -599.253    4643.791\npopulation_group[T.Multiple visible minorities]                                                   1510.4744   1566.479      0.964      0.335   -1560.048    4580.997\npopulation_group[T.Not a visible minority]                                                        7080.2409    830.537      8.525      0.000    5452.271    8708.211\npopulation_group[T.South Asian]                                                                   3913.3216    916.485      4.270      0.000    2116.881    5709.762\npopulation_group[T.Southeast Asian]                                                               3982.6957   1523.882      2.614      0.009     995.669    6969.722\npopulation_group[T.Visible minority, n.i.e.]                                                      -236.2114   2225.611     -0.106      0.915   -4598.726    4126.303\npopulation_group[T.West Asian]                                                                    -480.3772   1563.157     -0.307      0.759   -3544.388    2583.633\ngender[T.Woman]                                                                                  -5125.9304    238.112    -21.527      0.000   -5592.664   -4659.197\nfield_of_study[T.Architecture, engineering, and related trades]                                   1.222e+04    773.003     15.810      0.000    1.07e+04    1.37e+04\nfield_of_study[T.Business, management and public administration]                                  6107.6780    735.752      8.301      0.000    4665.499    7549.857\nfield_of_study[T.Education]                                                                       5440.3162    802.552      6.779      0.000    3867.201    7013.432\nfield_of_study[T.Health and related fields]                                                        1.46e+04    742.667     19.654      0.000    1.31e+04    1.61e+04\nfield_of_study[T.Humanities]                                                                     -1.646e+04    889.428    -18.501      0.000   -1.82e+04   -1.47e+04\nfield_of_study[T.Mathematics, computer and information sciences]                                  1.145e+04    937.390     12.218      0.000    9615.353    1.33e+04\nfield_of_study[T.Other instructional programs]                                                     379.5514   1831.190      0.207      0.836   -3209.841    3968.944\nfield_of_study[T.Personal, protective and transportation services]                                5628.9218    863.972      6.515      0.000    3935.414    7322.429\nfield_of_study[T.Physical and life sciences and technologies]                                    -1.181e+04    920.498    -12.828      0.000   -1.36e+04      -1e+04\nfield_of_study[T.Social and behavioural sciences and law]                                        -6424.9352    749.447     -8.573      0.000   -7893.959   -4955.912\nfield_of_study[T.Visual and performing arts, and communications technologies]                    -1.791e+04    864.314    -20.719      0.000   -1.96e+04   -1.62e+04\n==============================================================================\nOmnibus:                     2494.437   Durbin-Watson:                   1.994\nProb(Omnibus):                  0.000   Jarque-Bera (JB):            18759.776\nSkew:                           0.698   Prob(JB):                         0.00\nKurtosis:                       8.646   Cond. No.                         117.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n:::\n\nOverall, this model performed reasonably well. The Adjusted R-squared ($0.649$ in R and $0.648$ in Python) indicates that this model can explain ~64.85% of the variance in median post-graduation income. This number, while not extremely high, provides a good baseline prediction for a complex social and economic dataset. The F-statistic also indicates that this model is doing well. With a p-value of $p < 2.2 \\times 10^{-16}$), the model as a whole is statistically significant compared to an intercept-only model, which indicates that the explanatory variables used here do a decent job of explaining income differences. \n\nWe can interpret the coefficients from our model as well. The below interpretation uses the values from the R model, but similar interpretations can be made from the Python model as well. The intercept ($\\$31,044$) represents the baseline predicted median income for the reference group (i.e. graduates in the group of \"Man\" and \"Arab\", with education in \"Career, technical or professional training certificate\", and \"Agriculture, natural resources and conservation\"). All coefficients represent the expected difference in median income relative to the reference category, holding all other variables constant:\n\n* **Gender:** Being a woman, compared to being a man, is associated with a median income that is $\\$4,884$ lower, while holding all other variables constant. \n* **Population Group:** Several groups show significant differences relative to the baseline group, \"Arab\". For example, \"Not a visible minority\" shows an estimated increase of $\\$7,136$, while groups like Japanese, Multiple visible minorities, and West Asian do not show statistically significant differences ($p > 0.05$) after controlling for education, gender, and field of study.\n* **Educational qualification:** Higher degrees show higher median incomes, as is expected. For example, a Doctoral degree is associated with an increase of $\\$54,592$, and a Professional degree with an increase of about $\\$56,240$, while holding all other variables constant. \n* **Field of Study:** Fields like Health and related fields ($\\approx +\\$14,448$) and Architecture and engineering ($\\approx +\\$12,102$) show large positive coefficients, whereas fields like Visual and performing arts ($\\approx -\\$17,637$) and Humanities ($\\approx -\\$16,249$) show substantial negative adjustments compared to the baseline field of \"Agriculture, natural resources and conservation\". \n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict on test data\ntest_results_weighted <- income_test_weighted %>%\n  mutate(.pred = predict(model_lm_weighted, newdata = income_test_weighted))\n\n# Calculate weighted RMSE\ntest_results_weighted %>%\n  summarize(\n    weighted_mse = sum(number_graduates * (median_income - .pred)^2, na.rm = TRUE) / sum(number_graduates, na.rm = TRUE),\n    weighted_rmse = sqrt(weighted_mse)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  weighted_mse weighted_rmse\n         <dbl>         <dbl>\n1   147262780.        12135.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display income range for comparison\ncat(sprintf(\"Minimum median income: $%s\\n\", format(min(income_data$median_income), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimum median income: $3,900\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Maximum median income: $%s\\n\", format(max(income_data$median_income), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum median income: $270,200\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Mean median income: $%s\\n\", format(round(mean(income_data$median_income), 0), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean median income: $62,173\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Predict on test data\nincome_test_weighted = income_test_weighted.copy()\nincome_test_weighted[\".pred\"] = model_lm_weighted.predict(income_test_weighted)\n\n# Calculate weighted RMSE\nweights = income_test_weighted[\"number_graduates\"]\nactual = income_test_weighted[\"median_income\"]\npred = income_test_weighted[\".pred\"]\n\nweighted_mse = np.sum(weights * (actual - pred) ** 2) / np.sum(weights)\nweighted_rmse = np.sqrt(weighted_mse)\n\nprint(f\"Weighted RMSE: {weighted_rmse:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWeighted RMSE: 11009.3219\n```\n\n\n:::\n\n```{.python .cell-code}\n# Display income range and mean for comparison \nmin_inc = income_data[\"median_income\"].min()\nmax_inc = income_data[\"median_income\"].max()\nmean_inc = income_data[\"median_income\"].mean()\n\nprint(f\"Minimum median income: ${min_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimum median income: $3,900\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Maximum median income: ${max_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum median income: $270,200\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Mean median income: ${mean_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean median income: $62,173\n```\n\n\n:::\n:::\n\n:::\n\nTo further evaluate our model's generalizability, we can generate predictions on the test set and calculate the weighted root mean squared error (RMSE). The resulting test RMSE is $\\$12,135$ in R and $\\$11,009$ in Python. \n\nTo put this error into perspective, we can compare it against the broader distribution of median incomes in our dataset, which spans from $\\$3,900$ to $\\$270,200$ with a mean of $\\$62,173$. An RMSE of roughly $\\$12,000$. represents about 20% of the average income value. This indicates that while there is room for higher precision, the model captures the overall trend effectively without large-scale deviation.\n\nTo ground our evaluation in a concrete example, we can inspect a single row from our test set. By comparing the model's predicted income against the true reported value for this group, we can see how the model performs on an individual data point while accounting for its corresponding sample weight.\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select a single row from the test set (e.g. the first row)\nexample_row <- income_test_weighted |> \n  slice(2)\n\n# Generate the prediction for this specific row\nexample_pred <- predict(model_lm_weighted, newdata = example_row)\n\n# Calculate difference in predicted and true median incomes\nex_true <- example_row$median_income\nex_diff <- abs(ex_true - example_pred)\n\n# Display the attributes and values of our test case\ncat(sprintf(\"Educational Qualification: %s\\n\", example_row$educational_qualification))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEducational Qualification: Career, technical or professional training certificate\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Field of Study: %s\\n\", example_row$field_of_study))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nField of Study: Education\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Gender: %s\\n\", example_row$gender))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGender: Woman\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Population Group: %s\\n\", example_row$population_group))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPopulation Group: Not a visible minority\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Number of Graduates in Group (Weight): %s\\n\", format(example_row$number_graduates, big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Graduates in Group (Weight): 80\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"True Median Income: $%s\\n\", format(round(ex_true, 2), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue Median Income: $33,200\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Predicted Median Income: $%s\\n\", format(round(example_pred, 2), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted Median Income: $39,047.64\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Absolute Error: $%s\\n\", format(round(ex_diff, 2), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAbsolute Error: $5,847.64\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Select a single row from the test set\nexample_row = income_test_weighted.iloc[[1]]\n\n# Generate the prediction for this specific row\nexample_pred = model_lm_weighted.predict(example_row).iloc[0]\n\n# Calculate difference in predicted and true median incomes\nex_true = example_row[\"median_income\"].values[0]\nex_diff = abs(ex_true - example_pred)\n\n# Extract attributes for easy printing\nex_edu = example_row[\"educational_qualification\"].values[0]\nex_field = example_row[\"field_of_study\"].values[0]\nex_gender = example_row[\"gender\"].values[0]\nex_pop = example_row[\"population_group\"].values[0]\nex_grads = example_row[\"number_graduates\"].values[0]\n\n# Display the attributes and values (equivalent to cat/sprintf statements)\nprint(f\"Educational Qualification: {ex_edu}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEducational Qualification: Career, technical or professional training certificate\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Field of Study: {ex_field}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nField of Study: Personal, protective and transportation services\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Gender: {ex_gender}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGender: Man\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Population Group: {ex_pop}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPopulation Group: Not a visible minority\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Number of Graduates in Group (Weight): {ex_grads:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Graduates in Group (Weight): 120\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"True Median Income: ${ex_true:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue Median Income: $53,600.00\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Predicted Median Income: ${example_pred:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted Median Income: $44,127.87\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Absolute Error: ${ex_diff:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAbsolute Error: $9,472.13\n```\n\n\n:::\n:::\n\n:::\n\nLooking at this specific test case of a group of graduates from our test set, the true median income and our model's predicted median income give us a clear concrete example of how the model performs on an individual level. \n\nGiven that our test set RMSE is $\\$11,000$ to $\\$12,000$, individual discrepancies like this align fairly well with our overall error metrics. It illustrates that while the model captures the structural baseline and general trajectory of graduate earnings quite well, localized variance among specific demographic and educational intersections can still produce deviations of around five to twenty thousand dollars.\n\n\n\n\n##### Predictive Model with Interaction Effects\n\nAbove, we used a solely additive model, meaning that we assumed that the effects of each explanatory variable on the income prediction were independent of each other. Let's investigate an interactive model, which allows the effect of one variable to depend on the level of another. We will examine whether gender wage disparities vary across different academic areas, by incorporating interaction terms between gender and field of study into our model. This allows us to test whether specific fields exhibit wider or narrower wage gaps between men and women, after controlling for educational qualifications and population groups. It is important to note here, that we are restricting this investigation to only interaction terms between two variables, gender and field of study, as including interaction terms between all four explanatory variables can lead to severe overfitting, singularities due to uncommon combinations, and uninterpretable parameter explosion. These issues, and methods to work around them, are discussed further [here](https://medium.com/@TingyuZou/when-analyzing-complex-data-researchers-often-encounter-relationships-that-cannot-be-captured-by-1d9dccf14583). \n\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a weighted linear model with interaction effects\nmodel_lm_inter <- lm(median_income ~ (educational_qualification + population_group + gender * field_of_study), \n               data = income_train_weighted,\n               weights = number_graduates)\n\n# View coefficients and summary\nsummary(model_lm_inter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = median_income ~ (educational_qualification + population_group + \n    gender * field_of_study), data = income_train_weighted, weights = number_graduates)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-917241  -65197    4583   78893 1389455 \n\nCoefficients:\n                                                                                              Estimate\n(Intercept)                                                                                   32200.24\neducational_qualificationCareer, technical or professional training diploma                    8990.91\neducational_qualificationCareer, technical or professional training short credential          14542.90\neducational_qualificationDoctoral degree                                                      54825.51\neducational_qualificationMaster's degree                                                      47595.22\neducational_qualificationMaster's diploma                                                     43821.20\neducational_qualificationPost career, technical or professional training program certificate  25267.54\neducational_qualificationPost-baccalaureate non-graduate diploma                              52737.54\neducational_qualificationProfessional degree                                                  57290.70\neducational_qualificationUndergraduate certificate                                            26118.09\neducational_qualificationUndergraduate degree                                                 24396.16\npopulation_groupBlack                                                                          2080.87\npopulation_groupChinese                                                                        6157.85\npopulation_groupFilipino                                                                       5159.39\npopulation_groupJapanese                                                                       9484.35\npopulation_groupKorean                                                                         5628.40\npopulation_groupLatin American                                                                 2368.05\npopulation_groupMultiple visible minorities                                                    1510.99\npopulation_groupNot a visible minority                                                         7340.95\npopulation_groupSouth Asian                                                                    4236.85\npopulation_groupSoutheast Asian                                                                3290.69\npopulation_groupVisible minority, n.i.e.                                                         16.05\npopulation_groupWest Asian                                                                    -1230.80\ngenderWoman                                                                                   -7204.78\nfield_of_studyArchitecture, engineering, and related trades                                   10890.22\nfield_of_studyBusiness, management and public administration                                   5390.69\nfield_of_studyEducation                                                                        6342.14\nfield_of_studyHealth and related fields                                                        6115.10\nfield_of_studyHumanities                                                                     -21039.64\nfield_of_studyMathematics, computer and information sciences                                  11622.82\nfield_of_studyOther instructional programs                                                      467.90\nfield_of_studyPersonal, protective and transportation services                                 8780.36\nfield_of_studyPhysical and life sciences and technologies                                    -15155.20\nfield_of_studySocial and behavioural sciences and law                                         -8998.79\nfield_of_studyVisual and performing arts, and communications technologies                    -21459.08\ngenderWoman:field_of_studyArchitecture, engineering, and related trades                         964.57\ngenderWoman:field_of_studyBusiness, management and public administration                        189.76\ngenderWoman:field_of_studyEducation                                                            -250.65\ngenderWoman:field_of_studyHealth and related fields                                           10596.81\ngenderWoman:field_of_studyHumanities                                                           7381.67\ngenderWoman:field_of_studyMathematics, computer and information sciences                      -5435.29\ngenderWoman:field_of_studyOther instructional programs                                         1444.21\ngenderWoman:field_of_studyPersonal, protective and transportation services                    -9159.12\ngenderWoman:field_of_studyPhysical and life sciences and technologies                          4558.32\ngenderWoman:field_of_studySocial and behavioural sciences and law                              3517.73\ngenderWoman:field_of_studyVisual and performing arts, and communications technologies          6138.40\n                                                                                             Std. Error\n(Intercept)                                                                                     1466.07\neducational_qualificationCareer, technical or professional training diploma                      388.47\neducational_qualificationCareer, technical or professional training short credential             634.54\neducational_qualificationDoctoral degree                                                        1202.12\neducational_qualificationMaster's degree                                                         475.07\neducational_qualificationMaster's diploma                                                       1043.13\neducational_qualificationPost career, technical or professional training program certificate     751.96\neducational_qualificationPost-baccalaureate non-graduate diploma                                1929.40\neducational_qualificationProfessional degree                                                     814.76\neducational_qualificationUndergraduate certificate                                               639.35\neducational_qualificationUndergraduate degree                                                    379.92\npopulation_groupBlack                                                                            947.08\npopulation_groupChinese                                                                          922.58\npopulation_groupFilipino                                                                        1087.32\npopulation_groupJapanese                                                                        7280.31\npopulation_groupKorean                                                                          1849.03\npopulation_groupLatin American                                                                  1293.89\npopulation_groupMultiple visible minorities                                                     1527.07\npopulation_groupNot a visible minority                                                           819.26\npopulation_groupSouth Asian                                                                      903.68\npopulation_groupSoutheast Asian                                                                 1517.66\npopulation_groupVisible minority, n.i.e.                                                        2146.65\npopulation_groupWest Asian                                                                      1519.39\ngenderWoman                                                                                     1448.27\nfield_of_studyArchitecture, engineering, and related trades                                     1206.12\nfield_of_studyBusiness, management and public administration                                    1212.81\nfield_of_studyEducation                                                                         1455.16\nfield_of_studyHealth and related fields                                                         1298.67\nfield_of_studyHumanities                                                                        1488.44\nfield_of_studyMathematics, computer and information sciences                                    1332.31\nfield_of_studyOther instructional programs                                                      3353.40\nfield_of_studyPersonal, protective and transportation services                                  1349.47\nfield_of_studyPhysical and life sciences and technologies                                       1486.71\nfield_of_studySocial and behavioural sciences and law                                           1261.78\nfield_of_studyVisual and performing arts, and communications technologies                       1430.56\ngenderWoman:field_of_studyArchitecture, engineering, and related trades                         1631.91\ngenderWoman:field_of_studyBusiness, management and public administration                        1507.81\ngenderWoman:field_of_studyEducation                                                             1738.59\ngenderWoman:field_of_studyHealth and related fields                                             1579.59\ngenderWoman:field_of_studyHumanities                                                            1842.26\ngenderWoman:field_of_studyMathematics, computer and information sciences                        1991.69\ngenderWoman:field_of_studyOther instructional programs                                          3926.12\ngenderWoman:field_of_studyPersonal, protective and transportation services                      1769.35\ngenderWoman:field_of_studyPhysical and life sciences and technologies                           1862.16\ngenderWoman:field_of_studySocial and behavioural sciences and law                               1550.66\ngenderWoman:field_of_studyVisual and performing arts, and communications technologies           1794.24\n                                                                                             t value\n(Intercept)                                                                                   21.964\neducational_qualificationCareer, technical or professional training diploma                   23.144\neducational_qualificationCareer, technical or professional training short credential          22.919\neducational_qualificationDoctoral degree                                                      45.608\neducational_qualificationMaster's degree                                                     100.187\neducational_qualificationMaster's diploma                                                     42.009\neducational_qualificationPost career, technical or professional training program certificate  33.602\neducational_qualificationPost-baccalaureate non-graduate diploma                              27.334\neducational_qualificationProfessional degree                                                  70.316\neducational_qualificationUndergraduate certificate                                            40.851\neducational_qualificationUndergraduate degree                                                 64.214\npopulation_groupBlack                                                                          2.197\npopulation_groupChinese                                                                        6.675\npopulation_groupFilipino                                                                       4.745\npopulation_groupJapanese                                                                       1.303\npopulation_groupKorean                                                                         3.044\npopulation_groupLatin American                                                                 1.830\npopulation_groupMultiple visible minorities                                                    0.989\npopulation_groupNot a visible minority                                                         8.960\npopulation_groupSouth Asian                                                                    4.688\npopulation_groupSoutheast Asian                                                                2.168\npopulation_groupVisible minority, n.i.e.                                                       0.007\npopulation_groupWest Asian                                                                    -0.810\ngenderWoman                                                                                   -4.975\nfield_of_studyArchitecture, engineering, and related trades                                    9.029\nfield_of_studyBusiness, management and public administration                                   4.445\nfield_of_studyEducation                                                                        4.358\nfield_of_studyHealth and related fields                                                        4.709\nfield_of_studyHumanities                                                                     -14.135\nfield_of_studyMathematics, computer and information sciences                                   8.724\nfield_of_studyOther instructional programs                                                     0.140\nfield_of_studyPersonal, protective and transportation services                                 6.507\nfield_of_studyPhysical and life sciences and technologies                                    -10.194\nfield_of_studySocial and behavioural sciences and law                                         -7.132\nfield_of_studyVisual and performing arts, and communications technologies                    -15.001\ngenderWoman:field_of_studyArchitecture, engineering, and related trades                        0.591\ngenderWoman:field_of_studyBusiness, management and public administration                       0.126\ngenderWoman:field_of_studyEducation                                                           -0.144\ngenderWoman:field_of_studyHealth and related fields                                            6.709\ngenderWoman:field_of_studyHumanities                                                           4.007\ngenderWoman:field_of_studyMathematics, computer and information sciences                      -2.729\ngenderWoman:field_of_studyOther instructional programs                                         0.368\ngenderWoman:field_of_studyPersonal, protective and transportation services                    -5.177\ngenderWoman:field_of_studyPhysical and life sciences and technologies                          2.448\ngenderWoman:field_of_studySocial and behavioural sciences and law                              2.269\ngenderWoman:field_of_studyVisual and performing arts, and communications technologies          3.421\n                                                                                             Pr(>|t|)\n(Intercept)                                                                                   < 2e-16\neducational_qualificationCareer, technical or professional training diploma                   < 2e-16\neducational_qualificationCareer, technical or professional training short credential          < 2e-16\neducational_qualificationDoctoral degree                                                      < 2e-16\neducational_qualificationMaster's degree                                                      < 2e-16\neducational_qualificationMaster's diploma                                                     < 2e-16\neducational_qualificationPost career, technical or professional training program certificate  < 2e-16\neducational_qualificationPost-baccalaureate non-graduate diploma                              < 2e-16\neducational_qualificationProfessional degree                                                  < 2e-16\neducational_qualificationUndergraduate certificate                                            < 2e-16\neducational_qualificationUndergraduate degree                                                 < 2e-16\npopulation_groupBlack                                                                        0.028028\npopulation_groupChinese                                                                      2.58e-11\npopulation_groupFilipino                                                                     2.11e-06\npopulation_groupJapanese                                                                     0.192686\npopulation_groupKorean                                                                       0.002339\npopulation_groupLatin American                                                               0.067244\npopulation_groupMultiple visible minorities                                                  0.322453\npopulation_groupNot a visible minority                                                        < 2e-16\npopulation_groupSouth Asian                                                                  2.78e-06\npopulation_groupSoutheast Asian                                                              0.030156\npopulation_groupVisible minority, n.i.e.                                                     0.994035\npopulation_groupWest Asian                                                                   0.417918\ngenderWoman                                                                                  6.62e-07\nfield_of_studyArchitecture, engineering, and related trades                                   < 2e-16\nfield_of_studyBusiness, management and public administration                                 8.87e-06\nfield_of_studyEducation                                                                      1.32e-05\nfield_of_studyHealth and related fields                                                      2.52e-06\nfield_of_studyHumanities                                                                      < 2e-16\nfield_of_studyMathematics, computer and information sciences                                  < 2e-16\nfield_of_studyOther instructional programs                                                   0.889033\nfield_of_studyPersonal, protective and transportation services                               7.97e-11\nfield_of_studyPhysical and life sciences and technologies                                     < 2e-16\nfield_of_studySocial and behavioural sciences and law                                        1.04e-12\nfield_of_studyVisual and performing arts, and communications technologies                     < 2e-16\ngenderWoman:field_of_studyArchitecture, engineering, and related trades                      0.554486\ngenderWoman:field_of_studyBusiness, management and public administration                     0.899853\ngenderWoman:field_of_studyEducation                                                          0.885369\ngenderWoman:field_of_studyHealth and related fields                                          2.04e-11\ngenderWoman:field_of_studyHumanities                                                         6.19e-05\ngenderWoman:field_of_studyMathematics, computer and information sciences                     0.006361\ngenderWoman:field_of_studyOther instructional programs                                       0.712993\ngenderWoman:field_of_studyPersonal, protective and transportation services                   2.29e-07\ngenderWoman:field_of_studyPhysical and life sciences and technologies                        0.014384\ngenderWoman:field_of_studySocial and behavioural sciences and law                            0.023312\ngenderWoman:field_of_studyVisual and performing arts, and communications technologies        0.000625\n                                                                                                \n(Intercept)                                                                                  ***\neducational_qualificationCareer, technical or professional training diploma                  ***\neducational_qualificationCareer, technical or professional training short credential         ***\neducational_qualificationDoctoral degree                                                     ***\neducational_qualificationMaster's degree                                                     ***\neducational_qualificationMaster's diploma                                                    ***\neducational_qualificationPost career, technical or professional training program certificate ***\neducational_qualificationPost-baccalaureate non-graduate diploma                             ***\neducational_qualificationProfessional degree                                                 ***\neducational_qualificationUndergraduate certificate                                           ***\neducational_qualificationUndergraduate degree                                                ***\npopulation_groupBlack                                                                        *  \npopulation_groupChinese                                                                      ***\npopulation_groupFilipino                                                                     ***\npopulation_groupJapanese                                                                        \npopulation_groupKorean                                                                       ** \npopulation_groupLatin American                                                               .  \npopulation_groupMultiple visible minorities                                                     \npopulation_groupNot a visible minority                                                       ***\npopulation_groupSouth Asian                                                                  ***\npopulation_groupSoutheast Asian                                                              *  \npopulation_groupVisible minority, n.i.e.                                                        \npopulation_groupWest Asian                                                                      \ngenderWoman                                                                                  ***\nfield_of_studyArchitecture, engineering, and related trades                                  ***\nfield_of_studyBusiness, management and public administration                                 ***\nfield_of_studyEducation                                                                      ***\nfield_of_studyHealth and related fields                                                      ***\nfield_of_studyHumanities                                                                     ***\nfield_of_studyMathematics, computer and information sciences                                 ***\nfield_of_studyOther instructional programs                                                      \nfield_of_studyPersonal, protective and transportation services                               ***\nfield_of_studyPhysical and life sciences and technologies                                    ***\nfield_of_studySocial and behavioural sciences and law                                        ***\nfield_of_studyVisual and performing arts, and communications technologies                    ***\ngenderWoman:field_of_studyArchitecture, engineering, and related trades                         \ngenderWoman:field_of_studyBusiness, management and public administration                        \ngenderWoman:field_of_studyEducation                                                             \ngenderWoman:field_of_studyHealth and related fields                                          ***\ngenderWoman:field_of_studyHumanities                                                         ***\ngenderWoman:field_of_studyMathematics, computer and information sciences                     ** \ngenderWoman:field_of_studyOther instructional programs                                          \ngenderWoman:field_of_studyPersonal, protective and transportation services                   ***\ngenderWoman:field_of_studyPhysical and life sciences and technologies                        *  \ngenderWoman:field_of_studySocial and behavioural sciences and law                            *  \ngenderWoman:field_of_studyVisual and performing arts, and communications technologies        ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 144700 on 13261 degrees of freedom\nMultiple R-squared:  0.6605,\tAdjusted R-squared:  0.6594 \nF-statistic: 573.4 on 45 and 13261 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Fit the weighted linear model with interactions \nmodel_lm_inter = smf.wls(\n    formula=\"median_income ~ educational_qualification + population_group + gender * field_of_study\",\n    data=income_train_weighted,\n    weights=income_train_weighted[\"number_graduates\"]\n).fit()\n\n# View coefficients and summary\nprint(model_lm_inter.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            WLS Regression Results                            \n==============================================================================\nDep. Variable:          median_income   R-squared:                       0.659\nModel:                            WLS   Adj. R-squared:                  0.658\nMethod:                 Least Squares   F-statistic:                     570.0\nDate:                Tue, 15 Sep 2026   Prob (F-statistic):               0.00\nTime:                        10:54:36   Log-Likelihood:            -1.4870e+05\nNo. Observations:               13308   AIC:                         2.975e+05\nDf Residuals:                   13262   BIC:                         2.978e+05\nDf Model:                          45                                         \nCovariance Type:            nonrobust                                         \n====================================================================================================================================================================\n                                                                                                       coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------------------------------------------------------------------------------------\nIntercept                                                                                         3.264e+04   1446.379     22.563      0.000    2.98e+04    3.55e+04\neducational_qualification[T.Career, technical or professional training diploma]                   8472.5796    404.698     20.936      0.000    7679.313    9265.846\neducational_qualification[T.Career, technical or professional training short credential]          1.444e+04    647.288     22.312      0.000    1.32e+04    1.57e+04\neducational_qualification[T.Doctoral degree]                                                      5.508e+04   1225.550     44.946      0.000    5.27e+04    5.75e+04\neducational_qualification[T.Master's degree]                                                      4.757e+04    483.896     98.305      0.000    4.66e+04    4.85e+04\neducational_qualification[T.Master's diploma]                                                     4.349e+04   1088.264     39.959      0.000    4.14e+04    4.56e+04\neducational_qualification[T.Post career, technical or professional training program certificate]  2.542e+04    766.004     33.179      0.000    2.39e+04    2.69e+04\neducational_qualification[T.Post-baccalaureate non-graduate diploma]                              5.654e+04   2060.308     27.441      0.000    5.25e+04    6.06e+04\neducational_qualification[T.Professional degree]                                                  5.715e+04    811.957     70.382      0.000    5.56e+04    5.87e+04\neducational_qualification[T.Undergraduate certificate]                                            2.509e+04    664.477     37.752      0.000    2.38e+04    2.64e+04\neducational_qualification[T.Undergraduate degree]                                                 2.394e+04    390.577     61.298      0.000    2.32e+04    2.47e+04\npopulation_group[T.Black]                                                                         2032.1085    949.993      2.139      0.032     169.986    3894.231\npopulation_group[T.Chinese]                                                                       5927.8824    927.195      6.393      0.000    4110.448    7745.317\npopulation_group[T.Filipino]                                                                      5370.9339   1089.296      4.931      0.000    3235.758    7506.110\npopulation_group[T.Japanese]                                                                      8346.4844   7686.914      1.086      0.278   -6720.965    2.34e+04\npopulation_group[T.Korean]                                                                        5265.7647   1918.164      2.745      0.006    1505.890    9025.640\npopulation_group[T.Latin American]                                                                2079.1957   1318.664      1.577      0.115    -505.574    4663.965\npopulation_group[T.Multiple visible minorities]                                                   1431.1598   1544.386      0.927      0.354   -1596.057    4458.376\npopulation_group[T.Not a visible minority]                                                        7214.1079    819.043      8.808      0.000    5608.666    8819.550\npopulation_group[T.South Asian]                                                                   3835.0681    903.645      4.244      0.000    2063.796    5606.341\npopulation_group[T.Southeast Asian]                                                               3837.9728   1502.489      2.554      0.011     892.881    6783.065\npopulation_group[T.Visible minority, n.i.e.]                                                      -286.3473   2194.283     -0.130      0.896   -4587.456    4014.761\npopulation_group[T.West Asian]                                                                    -638.3987   1541.123     -0.414      0.679   -3659.221    2382.423\ngender[T.Woman]                                                                                  -7490.0258   1427.823     -5.246      0.000   -1.03e+04   -4691.289\nfield_of_study[T.Architecture, engineering, and related trades]                                   1.099e+04   1186.808      9.260      0.000    8664.032    1.33e+04\nfield_of_study[T.Business, management and public administration]                                  5988.6283   1189.038      5.037      0.000    3657.944    8319.313\nfield_of_study[T.Education]                                                                       5774.5988   1432.394      4.031      0.000    2966.902    8582.296\nfield_of_study[T.Health and related fields]                                                       6442.9166   1275.425      5.052      0.000    3942.902    8942.931\nfield_of_study[T.Humanities]                                                                     -2.129e+04   1466.734    -14.514      0.000   -2.42e+04   -1.84e+04\nfield_of_study[T.Mathematics, computer and information sciences]                                  1.175e+04   1337.443      8.784      0.000    9126.806    1.44e+04\nfield_of_study[T.Other instructional programs]                                                     196.6113   3213.135      0.061      0.951   -6101.592    6494.814\nfield_of_study[T.Personal, protective and transportation services]                                8845.8045   1311.406      6.745      0.000    6275.261    1.14e+04\nfield_of_study[T.Physical and life sciences and technologies]                                    -1.476e+04   1456.568    -10.136      0.000   -1.76e+04   -1.19e+04\nfield_of_study[T.Social and behavioural sciences and law]                                        -8750.9667   1244.418     -7.032      0.000   -1.12e+04   -6311.730\nfield_of_study[T.Visual and performing arts, and communications technologies]                    -2.162e+04   1399.428    -15.447      0.000   -2.44e+04   -1.89e+04\ngender[T.Woman]:field_of_study[T.Architecture, engineering, and related trades]                    995.6301   1645.261      0.605      0.545   -2229.317    4220.578\ngender[T.Woman]:field_of_study[T.Business, management and public administration]                    80.4413   1491.235      0.054      0.957   -2842.592    3003.474\ngender[T.Woman]:field_of_study[T.Education]                                                        137.4598   1716.860      0.080      0.936   -3227.832    3502.751\ngender[T.Woman]:field_of_study[T.Health and related fields]                                       1.047e+04   1561.063      6.706      0.000    7409.001    1.35e+04\ngender[T.Woman]:field_of_study[T.Humanities]                                                      7428.2660   1817.122      4.088      0.000    3866.448     1.1e+04\ngender[T.Woman]:field_of_study[T.Mathematics, computer and information sciences]                 -4672.5343   1995.723     -2.341      0.019   -8584.437    -760.632\ngender[T.Woman]:field_of_study[T.Other instructional programs]                                     505.2715   3877.285      0.130      0.896   -7094.760    8105.303\ngender[T.Woman]:field_of_study[T.Personal, protective and transportation services]               -8752.1424   1742.551     -5.023      0.000   -1.22e+04   -5336.494\ngender[T.Woman]:field_of_study[T.Physical and life sciences and technologies]                     4884.1593   1841.317      2.653      0.008    1274.916    8493.403\ngender[T.Woman]:field_of_study[T.Social and behavioural sciences and law]                         3485.7229   1538.116      2.266      0.023     470.795    6500.650\ngender[T.Woman]:field_of_study[T.Visual and performing arts, and communications technologies]     5933.6453   1761.897      3.368      0.001    2480.075    9387.216\n==============================================================================\nOmnibus:                     2309.028   Durbin-Watson:                   1.985\nProb(Omnibus):                  0.000   Jarque-Bera (JB):            17653.594\nSkew:                           0.624   Prob(JB):                         0.00\nKurtosis:                       8.503   Cond. No.                         119.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n:::\n\n::: {.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict on test data\ntest_results_inter <- income_test_weighted %>%\n  mutate(.pred = predict(model_lm_inter, newdata = income_test_weighted))\n\n# Calculate weighted RMSE\ntest_results_inter %>%\n  summarize(\n    weighted_mse = sum(number_graduates * (median_income - .pred)^2, na.rm = TRUE) / sum(number_graduates, na.rm = TRUE),\n    weighted_rmse = sqrt(weighted_mse)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  weighted_mse weighted_rmse\n         <dbl>         <dbl>\n1   145146251.        12048.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display income range for comparison\ncat(sprintf(\"Minimum median income: $%s\\n\", format(min(income_data$median_income), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimum median income: $3,900\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Maximum median income: $%s\\n\", format(max(income_data$median_income), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum median income: $270,200\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Mean median income: $%s\\n\", format(round(mean(income_data$median_income), 0), big.mark = \",\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean median income: $62,173\n```\n\n\n:::\n:::\n\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Predict on test data using the interaction model\nincome_test_weighted = income_test_weighted.copy()\nincome_test_weighted[\".pred_inter\"] = model_lm_inter.predict(income_test_weighted)\n\n# Calculate weighted RMSE for the interaction model\nweights = income_test_weighted[\"number_graduates\"]\nactual = income_test_weighted[\"median_income\"]\npred_inter = income_test_weighted[\".pred_inter\"]\n\nweighted_mse_inter = np.sum(weights * (actual - pred_inter) ** 2) / np.sum(weights)\nweighted_rmse_inter = np.sqrt(weighted_mse_inter)\n\nprint(f\"Interaction Model Weighted RMSE: ${weighted_rmse_inter:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInteraction Model Weighted RMSE: $10,903\n```\n\n\n:::\n\n```{.python .cell-code}\n# Display income range and mean for comparison\nmin_inc = income_data[\"median_income\"].min()\nmax_inc = income_data[\"median_income\"].max()\nmean_inc = income_data[\"median_income\"].mean()\n\nprint(f\"Minimum median income: ${min_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimum median income: $3,900\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Maximum median income: ${max_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum median income: $270,200\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Mean median income: ${mean_inc:,.0f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean median income: $62,173\n```\n\n\n:::\n:::\n\n:::\n\nThe inclusion of the interactions between gender and field of study modestly improves model fit, raising the adjusted R-squared to $0.6594$ in R and $0.658$ in Python. Again, all below interpretations are based on the R model, but similar discussion can be made from the Python model as well. \n\nWhile a general baseline gender penalty persists across many fields, where women earn an estimated $\\$7,205$ less than men holding other factors constant, the magnitude of this gap varies significantly by discipline:\n\n* **Exacerbated Disparities in Tech & Trades:** In fields like **mathematics, computer, and information sciences** ($-\\$5,435$ interaction) and **personal, protective, and transportation services** ($-\\$9,159$ interaction), the negative interaction coefficients indicate a structurally wider gender gap.\n* **Neutralization in Health:** Conversely, **health and related fields** exhibit a significant positive interaction ($\\approx +\\$10,597$), which effectively neutralizes or reverses the baseline gender penalty in those specific credentials. \n\nThese findings suggest that post-graduation wage disparities are not uniform across the labor market, but are instead heavily mediated by the specific career paths graduates pursue. With further analysis and investigation, other interaction terms may be significant, and provide more detailed insights into wage disparities. \n\n\n### Discussion\n\nThis analysis highlights some clear, persistent income gaps among recent Canadian graduates across gender, ethnicity, education levels, and fields of study. Our initial data exploration and hypothesis testing (using Kruskal-Wallis and Dunn's tests) confirmed that income distributions are not equal across gender and population groups, revealing statistically significant gaps, particularly when comparing visible minority groups to non-visible minority graduates.\n\nBuilding on that, our predictive models showed that a mix of education and demographic factors can explain about 66% of the variance in post-grad earnings. The baseline additive weighted model showed that higher degrees (like professional and doctoral credentials) and certain fields of study (like engineering and health) drive big earnings boosts, while a baseline wage penalty still sticks around for certain groups. \n\nTo dig deeper, adding gender-by-field-of-study interaction effects showed that wage gaps are not uniform across all areas of labor. While a general gap persists across many areas, fields like tech (math and computer science) and certain trades actually have wider gaps, while health-related fields manage to neutralize or even reverse the baseline penalty for women. \n\nEven with these insights, the analysis has some limitations. Because the dataset is aggregated at the group level instead of tracking individuals over time, our models rely on group weights and might miss smaller-scale details, like local cost-of-living differences or specific employer factors, that shape real-world earnings.\n\n\n\n\n## Attribution\n\nData sourced from Statistics Canada via the Government of Canada's Open Government Portal, available under an [Open Government Licence - Canada](https://open.canada.ca/en/open-government-licence-canada). Original dataset: [Characteristics and median employment income of Canadian postsecondary graduates two years after graduation, by visible minority group, educational qualification and field of study (primary groupings)](https://open.canada.ca/data/en/dataset/92554b64-fc13-427f-bbb2-f16b3436759c).\n\n",
    "supporting": [
      "postgradincome_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}