{
  "hash": "71b8e70d0d2b6bcfc5a23996b1fff4d2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Labour Force Status for Adults with Disabilities\"\ntoc: true\ntoc-depth: 4\ntoc-location: right\nsidebar: false\n---\n\n## About the Data\n\nThis dataset investigates the labour force status for adults with disabilities in Canada, categorized by disability type, global severity, age, sex, and geography. Compiled by Statistics Canada, this data provides a macro-level view of how intersecting demographic factors impact employment outcomes and labour market inclusion for individuals living with disabilities.\n\nHistorically, persons with disabilities in Canada face a substantial employment gap compared to the general population. [Research from Statistics Canada](https://www150.statcan.gc.ca/n1/daily-quotidien/231201/dq231201b-eng.htm) indicates that this gap is not uniform; it widens significantly as the severity of the disability increases and varies widely across different types of impairments. In fact, nearly three in five persons with disabilities or long-term conditions experience a labour market-related barrier. These structural hurdles span the entire employment lifecycle: from the hiring process to on-the-job challenges like navigating physical environments, inaccessible transportation, and unmet needs for modified work hours. While the recent rise in remote work has helped improve accommodation rates, these barriers continue to disproportionately affect specific demographics, particularly when intersected with gender, age, and regional economic differences, as detailed in recent findings on [workplace accommodations and flexible scheduling](https://www150.statcan.gc.ca/n1/pub/36-28-0001/2024008/article/00004-eng.htm) and [accessibility barriers in employment](https://www.statcan.gc.ca/en/sc/video/accessibility-barriers-employment).\n\nThese statistics are important for evaluating the efficacy of provincial and federal financial support systems (such as the [Canada Disability Benefit](https://www.canada.ca/en/services/benefits/disability/canada-disability-benefit.html) and provincial disability assistance programs) and highlight the systemic barriers that specific demographic groups face when seeking employment. This dataset enables researchers to statistically quantify these disparities and advocate for targeted vocational interventions.\n\n### Download\n\n<div class=\"button-container\">\n  <a href=\"../../data/clean/labourforcewithdisabilities.csv\" download class=\"download-button\">\n    Download CSV\n  </a>\n</div>\n\n### Metadata\n\n<div class=\"description-grid\">\n  <div class=\"field-label\">CSV Name</div><div class=\"field-value\">labourforcewithdisabilities.csv</div>\n  <div class=\"field-label\">Dataset Characteristics</div><div class=\"field-value\">Multivariate, Aggregated</div>\n  <div class=\"field-label\">Subject Area</div><div class=\"field-value\">Equity, Disability, Labour Economics</div>\n  <div class=\"field-label\">Associated Tasks</div><div class=\"field-value\">Regression, Comparative Analysis</div>\n  <div class=\"field-label\">Feature Type</div><div class=\"field-value\">Categorical, Numeric</div>\n  <div class=\"field-label\">Instances</div><div class=\"field-value\">4,343 records</div>\n  <div class=\"field-label\">Features</div><div class=\"field-value\">7</div>\n  <div class=\"field-label\">Has Missing Values?</div><div class=\"field-value\">No</div>\n</div>\n\n### Variables\n\n::: {.table-container}\n::: {.styled-table}\n\n| Variable Name           | Role      | Type        | Description                                                                 | Missing Values |\n|-------------------------|-----------|-------------|-----------------------------------------------------------------------------|----------------|\n| `geography`             | Feature   | Categorical | Province or territory location, e.g., \"Ontario\", \"British Columbia\"         | No             |\n| `sex`                   | Feature   | Categorical | Sex of the respondents: \"Males\" or \"Females\"                                | No             |\n| `age_group`             | Feature   | Categorical | Age bracket, e.g., \"15 to 24 years\", \"25 to 34 years\"                       | No             |\n| `disability_type`       | Feature   | Categorical | Specific impairment type or \"All disability types\"                          | No             |\n| `global_severity`       | Feature   | Categorical | Severity level: \"Mild\", \"Moderate\", \"Severe\", \"Very Severe\"                 | No             |\n| `labour_force_status`   | Feature   | Categorical | Status metric, e.g., \"Employment Rate\", \"Total labour force\"                | No             |\n| `value`                 | Feature   | Numeric     | The corresponding percentage rate or raw population headcount               | No             |\n\n:::\n:::\n\n\n::: {.cell}\n\n:::\n\n\n### Key Features of the Dataset\n\nEach row of this dataset represents an aggregated demographic group of adults with disabilities and reports their labour force status metrics:\n\n-   **Location** (`geography`) -- The Canadian province or territory of the respondents.\n-   **Demographic Information** (`sex`, `age_group`) -- Information on the sex and age bracket of the group.\n-   **Disability Profile** (`disability_type`, `global_severity`) -- The specific type of impairment and the overall severity level of the disability (ranging from Mild to Very Severe).\n-   **Labour Force Metric** (`labour_force_status`) -- The specific employment metric being reported, such as the employment rate, unemployment rate, or total labour force population count.\n-   **Reported Value** (`value`) -- The numerical percentage or population headcount corresponding to the labour force status.\n\n### Purpose and Use Cases\n\nThis dataset supports the analysis of:\n\n-   **Employment Equity & Barriers:** Examining how the severity and specific classification of a disability impact an individual's likelihood of securing employment.\n-   **Intersectionality in the Labour Market:** Evaluating the combined effects of age, sex, and varying levels of disability severity on workforce participation.\n-   **Geographic Disparities:** Comparing employment outcomes for individuals with disabilities across different Canadian provinces and territories to identify regional inequalities.\n-   **Predictive Modeling:** Building fractional regression baselines to estimate expected employment probabilities based on a combination of medical and demographic factors.\n-   **Institutional & Policy Insights:** Informing the distribution of federal and provincial social assistance (such as the Canada Disability Benefit), adjusting earnings exemption limits, and designing targeted vocational rehabilitation programs.\n\n## Case Study\n\n### Objective\n\nEquitable employment is a cornerstone of financial independence and social inclusion for adults living with disabilities. In Canada, federal and provincial governments provide essential financial assistance, such as the [Canada Disability Benefit (CDB)](https://www.canada.ca/en/services/benefits/disability/canada-disability-benefit.html) and provincial support programs, to help bridge the income gap. However, the reliance on these support systems and the ability to find sustainable employment are heavily influenced by a complex intersection of demographic factors.\n\nTo better understand the structural barriers within the Canadian labour market, this case study leverages Statistics Canada data to evaluate employment outcomes. We focus on several key questions:\n\n-   How does the global severity of a disability impact the likelihood of employment?\n-   Are there significant disparities in employment rates across different age groups and sexes?\n-   To what extent does geographical location (province or territory) affect labour force inclusion?\n\nBy conducting exploratory data analysis and fitting a regression model, we aim to statistically quantify the primary drivers of employment for individuals with disabilities. This analysis provides an educational framework for understanding how data can inform public policy, optimize vocational rehabilitation resources, and highlight regional or demographic gaps in the current society.\n\n### Analysis\n\n**Loading Libraries**\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\nlibrary(diversedata)      # Diverse Data Hub datasets\n\n# Core libraries\nlibrary(tidyverse)\nlibrary(knitr)\n\n# Statistical Modeling\nlibrary(broom)\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport diversedata as dd\nimport pandas as pd\nimport numpy as np\nfrom IPython.display import Markdown\nimport statsmodels.api as sm\nimport statsmodels.formula.api as smf\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n```\n:::\n\n:::\n\n#### 1. Data Cleaning & Processing\n\n**Note:** When working with aggregated government data, metrics like \"Employment Rate\" are often pre-calculated percentages. To use these in a logistical or fractional regression model, we must convert them into a 0-1 proportion.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading data\nlabour_force <- labourforcewithdisabilities\n\n# Filter for the target disability category to avoid double-counting\ndf_all_disabilities <- labour_force |>\n  filter(disability_type == 'All disability types')\n\n# Separate the employment rates from the population counts\ndf_rates <- df_all_disabilities |>\n  filter(labour_force_status == 'Employment Rate') |>\n  rename(employment_rate = value)\n\ndf_pop <- df_all_disabilities |>\n  filter(labour_force_status == 'Total labour force') |>\n  rename(population_weight = value)\n\n# Merge to align rates with their respective population weights\nmerge_cols <- c('geography', 'sex', 'age_group', 'global_severity')\n\nlabour_force_clean <- df_rates |>\n  select(all_of(merge_cols), employment_rate) |>\n  inner_join(df_pop |> select(all_of(merge_cols), population_weight), by = merge_cols) |>\n  drop_na(employment_rate, population_weight) |>\n  # Convert rate to a 0-1 proportion for the Fractional Logit model\n  mutate(employment_proportion = employment_rate / 100.0)\n\n# Preview data\nlabour_force_clean |>\n  head() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|geography                 |sex   |age_group      |global_severity | employment_rate| population_weight| employment_proportion|\n|:-------------------------|:-----|:--------------|:---------------|---------------:|-----------------:|---------------------:|\n|Newfoundland and Labrador |Males |15 to 24 years |Mild            |            23.8|               650|                 0.238|\n|Newfoundland and Labrador |Males |25 to 34 years |Mild            |            69.2|              1070|                 0.692|\n|Newfoundland and Labrador |Males |35 to 44 years |Mild            |            74.8|              1260|                 0.748|\n|Newfoundland and Labrador |Males |35 to 44 years |Moderate        |            43.6|               550|                 0.436|\n|Newfoundland and Labrador |Males |45 to 54 years |Mild            |            78.1|              2800|                 0.781|\n|Newfoundland and Labrador |Males |55 to 64 years |Mild            |            62.9|              1960|                 0.629|\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Reading data\nlabour_force = dd.load_data(\"labourforcewithdisabilities\")\n\n# Filter for the target disability category to avoid double-counting\ndf_all_disabilities = labour_force[labour_force['disability_type'] == 'All disability types']\n\n# Separate the employment rates from the population counts\ndf_rates = df_all_disabilities[df_all_disabilities['labour_force_status'] == 'Employment Rate'].copy()\ndf_pop = df_all_disabilities[df_all_disabilities['labour_force_status'] == 'Total labour force'].copy()\n\n# Rename the 'value' columns before merging\ndf_rates = df_rates.rename(columns={'value': 'employment_rate'})\ndf_pop = df_pop.rename(columns={'value': 'population_weight'})\n\n# Merge to align rates with their respective population weights\nmerge_cols = ['geography', 'sex', 'age_group', 'global_severity']\nlabour_force_clean = pd.merge(df_rates[merge_cols + ['employment_rate']], \n                    df_pop[merge_cols + ['population_weight']], \n                    on=merge_cols, \n                    how='inner')\n\n# Drop any rows with suppressed or missing data\nlabour_force_clean = labour_force_clean.dropna(subset=['employment_rate', 'population_weight'])\n\n# Convert rate to a 0-1 proportion for the Fractional Logit model\nlabour_force_clean['employment_proportion'] = labour_force_clean['employment_rate'] / 100.0\n\nMarkdown(labour_force_clean.head().to_markdown())\n```\n\n::: {.cell-output-display}\n|    | geography                 | sex   | age_group      | global_severity   |   employment_rate |   population_weight |   employment_proportion |\n|---:|:--------------------------|:------|:---------------|:------------------|------------------:|--------------------:|------------------------:|\n|  0 | Newfoundland and Labrador | Males | 15 to 24 years | Mild              |              23.8 |                 650 |                   0.238 |\n|  1 | Newfoundland and Labrador | Males | 25 to 34 years | Mild              |              69.2 |                1070 |                   0.692 |\n|  2 | Newfoundland and Labrador | Males | 35 to 44 years | Mild              |              74.8 |                1260 |                   0.748 |\n|  3 | Newfoundland and Labrador | Males | 35 to 44 years | Moderate          |              43.6 |                 550 |                   0.436 |\n|  4 | Newfoundland and Labrador | Males | 45 to 54 years | Mild              |              78.1 |                2800 |                   0.781 |\n:::\n:::\n\n:::\n\n#### 2. Exploratory Data Analysis\n\nBefore applying predictive modeling or inferential tests, visual exploration provides an intuitive baseline of how employment rates vary across individual demographic factors.\n\n------------------------------------------------------------------------\n\n**Employment Rate by Severity Level**\n\nThis visualization evaluates the relationship between disability severity and employment outcomes. It aggregates reported employment rates across four global severity tiers: Mild, Moderate, Severe, and Very Severe.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsev_order <- c(\"Mild\", \"Moderate\", \"Severe\", \"Very Severe\")\n\nggplot(labour_force_clean, aes(\n  x = employment_rate, \n  y = factor(global_severity, levels = rev(sev_order)), # rev() plots Mild at the top\n  fill = factor(global_severity, levels = sev_order)    # Maps light-to-dark logically\n)) +\n  stat_summary(fun = \"mean\", geom = \"bar\", width = 0.6) +\n  scale_fill_brewer(palette = \"Reds\") +\n  labs(\n    title = \"Mean Employment Rate by Severity Level\",\n    x = \"Employment Rate (%)\",\n    y = \"Global Severity\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 13),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_severity_r-1.png){width=768}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsev_order = [\"Mild\", \"Moderate\", \"Severe\", \"Very Severe\"]\n\nplt.figure(figsize=(8, 4.5))\nsns.barplot(\n    data=labour_force_clean,\n    x=\"employment_rate\",\n    y=\"global_severity\",\n    hue=\"global_severity\",\n    order=sev_order,\n    hue_order=sev_order,\n    errorbar=None,\n    palette=\"Reds\",\n    legend=False,\n    width=0.6,\n)\n\nplt.title(\"Mean Employment Rate by Severity Level\", fontsize=13, fontweight=\"bold\", pad=12)\nplt.xlabel(\"Employment Rate (%)\", fontsize=11)\nplt.ylabel(\"Global Severity\", fontsize=11)\nplt.grid(True, alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_severity_py-1.png){width=768}\n:::\n:::\n\n:::\n\nA clear negative trajectory emerges between impairment severity and labour market participation. Individuals classified with Mild disabilities experience employment rates approaching 70%, whereas the likelihood of holding a job declines sharply as severity transitions to Moderate, Severe, and Very Severe.\n\n------------------------------------------------------------------------\n\n**Employment Rate by Age Group**\n\nThis plot examines labour force engagement across different stages of working life, from youth entering the workforce to older adults approaching retirement.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_order <- c(\"15 to 24 years\", \"25 to 34 years\", \"35 to 44 years\", \"45 to 54 years\", \"55 to 64 years\")\n\nggplot(labour_force_clean, aes(\n  x = employment_rate, \n  y = factor(age_group, levels = rev(age_order)), \n  fill = factor(age_group, levels = age_order)\n)) +\n  stat_summary(fun = \"mean\", geom = \"bar\", width = 0.6) +\n  scale_fill_brewer(palette = \"Blues\") +\n  labs(\n    title = \"Mean Employment Rate by Age Group\",\n    x = \"Employment Rate (%)\",\n    y = \"Age Group\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 13),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_age_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_order = [\n    \"15 to 24 years\", \"25 to 34 years\", \n    \"35 to 44 years\", \"45 to 54 years\", \"55 to 64 years\"\n]\n\nplt.figure(figsize=(8, 4.5))\nsns.barplot(\n    data=labour_force_clean,\n    x=\"employment_rate\",\n    y=\"age_group\",\n    hue=\"age_group\",\n    order=age_order,\n    hue_order=age_order,\n    errorbar=None,\n    palette=\"Blues\",\n    legend=False,\n    width=0.6,\n)\n\nplt.title(\"Mean Employment Rate by Age Group\", fontsize=13, fontweight=\"bold\", pad=12)\nplt.xlabel(\"Employment Rate (%)\", fontsize=11)\nplt.ylabel(\"Age Group\", fontsize=11)\nplt.grid(True, alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_age_py-1.png){width=768}\n:::\n:::\n\n:::\n\nEmployment rates follow a distinct bell curve across age categories. Working-age adults in the core brackets (25 to 54 years) maintain the highest average employment rates. Conversely, youth (15 to 24 years) and older adults (55 to 64 years) experience substantial penalties, reflecting transition barriers for new labour market entrants and early exits from the workforce near retirement age.\n\n------------------------------------------------------------------------\n\n**Employment Rate by Sex**\n\nThis comparison breaks down average employment rates between men and women in the dataset to highlight sex-based participation gaps.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_order <- c(\"Females\", \"Males\")\n\nggplot(labour_force_clean, aes(\n  x = employment_rate, \n  y = factor(sex, levels = rev(sex_order)), \n  fill = factor(sex, levels = sex_order)\n)) +\n  stat_summary(fun = \"mean\", geom = \"bar\", width = 0.5) +\n  scale_fill_brewer(palette = \"Greens\") +\n  labs(\n    title = \"Mean Employment Rate by Sex\",\n    x = \"Employment Rate (%)\",\n    y = \"Sex\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 13),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_sex_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsex_order = [\"Females\", \"Males\"]\n\nplt.figure(figsize=(8, 3.5))\nsns.barplot(\n    data=labour_force_clean,\n    x=\"employment_rate\",\n    y=\"sex\",\n    hue=\"sex\",\n    order=sex_order,\n    hue_order=sex_order,\n    errorbar=None,\n    palette=\"Greens\",\n    legend=False,\n    width=0.5,\n)\n\nplt.title(\"Mean Employment Rate by Sex\", fontsize=13, fontweight=\"bold\", pad=12)\nplt.xlabel(\"Employment Rate (%)\", fontsize=11)\nplt.ylabel(\"Sex\", fontsize=11)\nplt.grid(True, alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_sex_py-1.png){width=768}\n:::\n:::\n\n:::\n\nMen display a marginally higher mean employment rate compared to women. While this gap is narrower than the disparities observed across age brackets or severity levels, it indicates that sex intersects with disability to shape workforce attachment.\n\n------------------------------------------------------------------------\n\n**Employment Rate by Province and Territory**\n\nThis chart displays geographic variation in employment rates across Canadian provinces and territories, ordered from highest to lowest mean employment rate.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(labour_force_clean, aes(\n  x = employment_rate, \n  y = reorder(geography, employment_rate, FUN = mean), \n  fill = reorder(geography, employment_rate, FUN = mean)\n)) +\n  stat_summary(fun = \"mean\", geom = \"bar\", width = 0.6) +\n  scale_fill_viridis_d(option = \"magma\") +\n  labs(\n    title = \"Mean Employment Rate by Province/Territory\",\n    subtitle = \"Ordered by Mean Employment Rate\",\n    x = \"Employment Rate (%)\",\n    y = \"Province / Territory\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 13),\n    plot.subtitle = element_text(color = \"gray40\", size = 10),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_geo_r-3.png){width=768}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Calculate means and order ascending to match R's color scaling\ngeo_means = labour_force_clean.groupby(\"geography\")[\"employment_rate\"].mean().sort_values(ascending=True)\ngeo_order_asc = geo_means.index.tolist()\n\n# Reverse for the y-axis so the highest value sits at the top of the plot\ngeo_order_desc = geo_order_asc[::-1]\n\nplt.figure(figsize=(8, 6))\nsns.barplot(\n    data=labour_force_clean,\n    x=\"employment_rate\",\n    y=\"geography\",\n    hue=\"geography\",\n    order=geo_order_desc,       # Plot highest at top\n    hue_order=geo_order_asc,    # Map magma lowest-to-highest to match R\n    errorbar=None,\n    palette=\"magma\",\n    legend=False,\n    width=0.6,\n)\n\nplt.title(\"Mean Employment Rate by Province/Territory\", fontsize=13, fontweight=\"bold\", pad=15, loc=\"left\")\nplt.xlabel(\"Employment Rate (%)\", fontsize=11)\nplt.ylabel(\"Province / Territory\", fontsize=11)\nplt.grid(True, alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](labourforcewithdisabilities_files/figure-html/eda_geo_py-1.png){width=768}\n:::\n:::\n\n:::\n\nRegional variations highlight differences in economic conditions and social support frameworks. Western provinces such as Saskatchewan and Alberta report higher average employment rates, while Quebec and Atlantic provinces tend to show lower baseline figures. Although northern territories (Yukon and Nunavut) appear at the top of the raw rankings, these estimates stem from smaller sample sizes with high suppression rates and require careful interpretation through weighted modeling.\n\n\n#### 3. Logistic Regression \n\n**Note:** We use a Generalized Linear Model (GLM) with a `Binomial` (or `quasibinomial`) family to handle fractional response variables (proportions between 0 and 1). By passing our population headcounts into the `weights` argument, the model evaluates the dataset as millions of surveyed individuals rather than treating each aggregated row equally. \n\n**Setting Reference Categories**\n\nBefore running a regression, the model needs a baseline to compare everything against. By explicitly setting reference groups, our final coefficients will clearly show the effect relative to: `Ontario`, `Males`, `25 to 34 years`, and `Mild` severity.\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Explicitly setting reference groups for the categorical variables directly in the dataframe\nlabour_force_clean <- labour_force_clean |>\n  mutate(\n    geography = relevel(factor(geography), ref = \"Ontario\"),\n    sex = relevel(factor(sex), ref = \"Males\"),\n    age_group = relevel(factor(age_group), ref = \"25 to 34 years\"),\n    global_severity = relevel(factor(global_severity), ref = \"Mild\")\n  )\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Define formula explicitly setting the reference group for each demographic\nformula = (\n    \"employment_proportion ~ \"\n    \"C(geography, Treatment(reference='Ontario')) + \"\n    \"C(sex, Treatment(reference='Males')) + \"\n    \"C(age_group, Treatment(reference='25 to 34 years')) + \"\n    \"C(global_severity, Treatment(reference='Mild'))\"\n)\n```\n:::\n\n\n:::\n\n**Fitting the Model**\n\nNext, we feed our prepared variables into the GLM. Because the outcome is a proportion, a standard linear model would be inappropriate; instead, the logit link transforms the data into log-odds.\n\n::: panel-tabset\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the GLM with quasibinomial family (to handle overdispersion) and population weights\nweighted_glm <- glm(\n  employment_proportion ~ geography + sex + age_group + global_severity,\n  data = labour_force_clean,\n  family = quasibinomial(link = \"logit\"),\n  weights = population_weight\n)\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Fit a GLM with Binomial family, population weights, \n# and Pearson's chi-squared scale to account for overdispersion (Quasibinomial equivalent)\nweighted_glm_py = smf.glm(\n    formula=formula, \n    data=labour_force_clean, \n    family=sm.families.Binomial(), \n    var_weights=labour_force_clean['population_weight']\n).fit(scale=\"X2\")\n```\n:::\n\n\n:::\n\n**Formatting the Output**\n\nRaw model output can be dense and difficult to read. In this final step, we clean up the summary statistics so they are presentation-ready.\n\n::: panel-tabset\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tidy the model output, round numbers for readability, and render a clean table\ntidy(weighted_glm) |>\n  mutate(across(where(is.numeric), ~round(.x, 3))) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term                               | estimate| std.error| statistic| p.value|\n|:----------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                        |    0.938|     0.142|     6.582|   0.000|\n|geographyAlberta                   |    0.563|     0.116|     4.863|   0.000|\n|geographyBritish Columbia          |    0.172|     0.103|     1.670|   0.097|\n|geographyManitoba                  |    0.470|     0.170|     2.764|   0.006|\n|geographyNew Brunswick             |    0.072|     0.285|     0.254|   0.800|\n|geographyNewfoundland and Labrador |    0.081|     0.402|     0.201|   0.841|\n|geographyNova Scotia               |    0.118|     0.186|     0.638|   0.524|\n|geographyNunavut                   |    0.309|     4.617|     0.067|   0.947|\n|geographyPrince Edward Island      |    0.223|     0.538|     0.414|   0.679|\n|geographyQuebec                    |   -0.074|     0.119|    -0.624|   0.533|\n|geographySaskatchewan              |    0.634|     0.208|     3.049|   0.003|\n|geographyYukon                     |    1.000|     1.841|     0.543|   0.588|\n|sexFemales                         |   -0.192|     0.072|    -2.680|   0.008|\n|age_group15 to 24 years            |   -1.241|     0.178|    -6.957|   0.000|\n|age_group35 to 44 years            |    0.186|     0.157|     1.184|   0.238|\n|age_group45 to 54 years            |    0.140|     0.146|     0.956|   0.340|\n|age_group55 to 64 years            |   -0.681|     0.141|    -4.839|   0.000|\n|global_severityModerate            |   -0.450|     0.094|    -4.806|   0.000|\n|global_severitySevere              |   -0.926|     0.091|   -10.180|   0.000|\n|global_severityVery Severe         |   -1.537|     0.151|   -10.172|   0.000|\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Print the formatted statsmodels summary table\nprint(weighted_glm_py.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Generalized Linear Model Regression Results                   \n=================================================================================\nDep. Variable:     employment_proportion   No. Observations:                  216\nModel:                               GLM   Df Residuals:                      196\nModel Family:                   Binomial   Df Model:                           19\nLink Function:                     Logit   Scale:                          409.17\nMethod:                             IRLS   Log-Likelihood:            -6.4739e+05\nDate:                   Mon, 14 Sep 2026   Deviance:                       84504.\nTime:                           16:58:06   Pearson chi2:                 8.02e+04\nNo. Iterations:                        6   Pseudo R-squ. (CS):              1.000\nCovariance Type:               nonrobust                                         \n=============================================================================================================================================\n                                                                                coef    std err          z      P>|z|      [0.025      0.975]\n---------------------------------------------------------------------------------------------------------------------------------------------\nIntercept                                                                     0.9377      0.142      6.582      0.000       0.658       1.217\nC(geography, Treatment(reference='Ontario'))[T.Alberta]                       0.5635      0.116      4.863      0.000       0.336       0.791\nC(geography, Treatment(reference='Ontario'))[T.British Columbia]              0.1720      0.103      1.670      0.095      -0.030       0.374\nC(geography, Treatment(reference='Ontario'))[T.Manitoba]                      0.4699      0.170      2.764      0.006       0.137       0.803\nC(geography, Treatment(reference='Ontario'))[T.New Brunswick]                 0.0722      0.285      0.254      0.800      -0.485       0.630\nC(geography, Treatment(reference='Ontario'))[T.Newfoundland and Labrador]     0.0808      0.402      0.201      0.841      -0.707       0.869\nC(geography, Treatment(reference='Ontario'))[T.Nova Scotia]                   0.1184      0.186      0.638      0.523      -0.245       0.482\nC(geography, Treatment(reference='Ontario'))[T.Nunavut]                       0.3087      4.617      0.067      0.947      -8.741       9.359\nC(geography, Treatment(reference='Ontario'))[T.Prince Edward Island]          0.2227      0.538      0.414      0.679      -0.831       1.277\nC(geography, Treatment(reference='Ontario'))[T.Quebec]                       -0.0742      0.119     -0.624      0.532      -0.307       0.159\nC(geography, Treatment(reference='Ontario'))[T.Saskatchewan]                  0.6344      0.208      3.049      0.002       0.227       1.042\nC(geography, Treatment(reference='Ontario'))[T.Yukon]                         1.0000      1.841      0.543      0.587      -2.609       4.608\nC(sex, Treatment(reference='Males'))[T.Females]                              -0.1924      0.072     -2.680      0.007      -0.333      -0.052\nC(age_group, Treatment(reference='25 to 34 years'))[T.15 to 24 years]        -1.2410      0.178     -6.957      0.000      -1.591      -0.891\nC(age_group, Treatment(reference='25 to 34 years'))[T.35 to 44 years]         0.1863      0.157      1.184      0.236      -0.122       0.495\nC(age_group, Treatment(reference='25 to 34 years'))[T.45 to 54 years]         0.1398      0.146      0.956      0.339      -0.147       0.427\nC(age_group, Treatment(reference='25 to 34 years'))[T.55 to 64 years]        -0.6809      0.141     -4.839      0.000      -0.957      -0.405\nC(global_severity, Treatment(reference='Mild'))[T.Moderate]                  -0.4496      0.094     -4.806      0.000      -0.633      -0.266\nC(global_severity, Treatment(reference='Mild'))[T.Severe]                    -0.9263      0.091    -10.180      0.000      -1.105      -0.748\nC(global_severity, Treatment(reference='Mild'))[T.Very Severe]               -1.5372      0.151    -10.172      0.000      -1.833      -1.241\n=============================================================================================================================================\n```\n\n\n:::\n:::\n\n\n:::\n\n#### 4. Log-Odds Calculation\n\nTo make sense of the model's coefficients, we have to remember they are in log-odds. We can convert these back to an intuitive probability (the expected employment rate) using the inverse-logit formula: \n\n$$Probability = \\frac{e^{log\\_odds}}{(1 + e^{log\\_odds})}$$\n\n**Example 1: The Baseline (Intercept)**\n\nThe model's `intercept` ($0.9377$) represents our reference group (a man, aged 25 to 34 years, located in Ontario, with a Mild disability). Plugging this into our formula,\n\n$$\\frac{e^{0.9377}}{1 + e^{0.9377}} = 0.7186...$$\n\ngives a baseline expected employment rate of 71.9%.\n\n**Example 2: Demographic Factors (Severity Level)**\n\nMoving from a Mild disability (the baseline) to a Severe disability carries a penalty of $-0.9263$. For our reference group, this changes the total log-odds to $0.0114$ ($0.9377 - 0.9263$). Passing that through our formula, \n\n$$\\frac{e^{0.0114}}{1 + e^{0.0114}} = 0.5028...$$\n\nthe expected employment rate drops to 50.3%. \n\nFor a Very Severe disability ($-1.5372$), log-odds drops to $-0.5995$ ($0.9377-1.5372$). Passing that through our formula, \n\n$$\\frac{e^{-0.5995}}{1 + e^{-0.5995}} = 0.3544...$$\n\n\nthe employment rate plummets to 35.4%.\n\n### Discussion\n\nThis analysis highlights the structural barriers to employment faced by adults with disabilities across the Canadian labour market. Our initial exploratory data analysis showed clear disparities in workforce participation, revealing a stark negative trajectory between disability severity and employment, alongside distinct age-related and regional gaps.\n\nBuilding on these visualizations, our logistic regression allowed us to quantify these penalties while controlling for intersectional demographic factors. By anchoring our model to a specific baseline (a man, aged 25 to 34, in Ontario, with a Mild disability), we translated log-odds into tangible, real-world probabilities. As demonstrated in our calculations, while this baseline group has an expected employment rate of 72%, the rate decreases rapidly as the level of severity increases. Shifting the severity from Mild to Very Severe cuts the expected employment rate by more than half, dropping it to roughly 35%.\n\nBeyond severity, the model highlights significant demographic hurdles. We observed substantial age penalties for youth (aged 15 to 24) and for older adults (aged 55 to 64) that reflect the distinct challenges of initially entering the workforce and the reality of premature exits for those approaching retirement.\n\nEven with these insights, it is important to approach these findings with caution due to the dataset's limitations. Because this data is aggregated at the demographic group level rather than tracking individual outcomes over time, our models rely on population weights and cannot account for granular, individual-level factors, such as the specific nature of a workplace accommodation, local transit accessibility, or isolated employer dynamics. Furthermore, high data sparsity and suppression in regions like Nunavut (reflected in high $p$-values) underscore the difficulty of drawing robust inferential conclusions for smaller populations. Despite these limitations, quantifying these statistical penalties provides a critical framework for policymakers to evaluate exactly where current social safety nets and vocational programs are succeeding, and where targeted interventions are most urgently needed.\n\n\n## Attribution\n\nData sourced from Statistics Canada via the Government of Canada's Open Government Portal, available under an Open Government Licence - Canada. Original dataset: [Labour force status for adults with disabilities by disability type](https://open.canada.ca/data/en/dataset/92aeb8dc-c7ca-4f44-81df-fdaf289d23fd).",
    "supporting": [
      "labourforcewithdisabilities_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}