on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libproj-dev \
            libudunits2-dev \
            libgdal-dev \
            libnode-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-v2-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-v2-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv", repos="https://cloud.r-project.org")
          options(renv.verbose = TRUE)
          renv::restore()

      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: diverse_web_env
          environment-file: environment.yml
          auto-activate-base: false
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

      # so diverse_web_env can be found by reticulate which allows
      # Python code to be executed in the .qmd files using the conda environment
      - name: Tell reticulate where conda is
        run: |
          echo "RETICULATE_PYTHON=$CONDA/envs/diverse_web_env/bin/python" >> $GITHUB_ENV

      - name: Hotfix for reticulate libexpat conflict
        run: |
          echo 'dyn.load("/home/runner/miniconda3/envs/diverse_web_env/lib/libexpat.so.1", local = FALSE, now = TRUE)' > .Rprofile

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
